### ISSUE TITLE
Import isn't working with FireFox Nightly

### ISSUE THREAD

**Issue by raguay** [go-shiori/shiori#102]
I am using FireFox nightly. I exported my bookmarks and tried to import them, but nothing is showing up. It's a list I've been using for many years and would love to move it over to this platform, other than had doing it as that would take a long time. 

macOS 10.13.5
go version go1.10.3 darwin/amd64

Thanks.

**Comment by RadhiFadlillah** [comment]
Hi @raguay, sorry for really late response.

I think it should be fixed by now, if so could you try it out again ?

Thank you.

**Comment by raguay** [comment]
Yes, that works. Thanks.
