### ISSUE TITLE
Config flag to enable disable swagger ui

### ISSUE THREAD

**Issue by Weav3r** [go-shiori/shiori#1025]
Please is it possible to provide a configuration variable to disable the swagger ui?
I think for non-developers just self-hosting having the swagger ui disabled would be helpful.
Thanks for all your hardwork and hope you consider this request.

**Comment by fmartingr** [comment]
Yeah, I think it makes more sense to have it disabled by default, actually.

**Comment by Weav3r** [comment]
I agree
