### ISSUE TITLE
No alpine-latest or alpine-dev docker image

### ISSUE THREAD

**Issue by Promix953** [go-shiori/shiori#1034]
## Data
- **Shiori version**: 1.7.2
- **Database Engine**: SQLite
- **Operating system**: Linux
- **CLI/Web interface/Web Extension**:

## Describe the bug / actual behavior
Actions does not build alpine-latest or alpine-dev images.

## Expected behavior
Ability to pull alpine-latest or alpine-dev images.

## To Reproduce
```
docker pull ghcr.io/go-shiori/shiori:alpine-latest
```

**Comment by fmartingr** [comment]
Hey, thanks for catching this one. I've fixed it in #1035 but it will have no effect until the next release. Until then you can use `alpine-v1.7.2-1-g306487a` which was just built from latest master.
