### ISSUE TITLE
Feature request: Annotating articles

### ISSUE THREAD

**Issue by ibnishak** [go-shiori/shiori#107]
Please add the ability to add annotations to the articles.

**Comment by RadhiFadlillah** [comment]
I'm sorry, but I don't think I could do this. 

First, I don't think annotation is the task for bookmark manager like Shiori. Second (and the main reason), it's quite hard to do and I think it will add too much complexity to code base.

**Comment by 8bitgentleman** [comment]
@RadhiFadlillah  I know you're not keen on adding annotation to shiori but have you considered integrating an open source annotation platform into shiori instead? I'm specifically thinking of [hypothes.is ](https://web.hypothes.is/help/overview-of-the-hypothesis-system/) which can be [embedded into applications, websites, and interfaces](https://web.hypothes.is/help/embedding-hypothesis-in-websites-and-platforms/) and works with either a publicly hosted central server or your own self-hosted solution. All their code is on [github](https://github.com/hypothesis) and their documentation is pretty good.

**Comment by Mohan-cloud** [comment]
I also think this will be a useful feature. Can this be revisited?

**Comment by KhaaL** [comment]
For those who want annotation built in, omnivore has this capability built-in, but I think its too big for if you have a small amount of users.

I recently discovered Shiori and find it really awesome - even though I sorely miss highlighting text, I respect @RadhiFadlillah  decision to keep the codebase small and lean.

**Comment by fmartingr** [comment]
Right now what I do is get the epub from the bookmark and annotate it in my tablet. Is not really convenient but easy to capture thoughts. Quotes go on to obsidian.

Just curious, since this issue predates me, how would this look on the UI? What are the expectations?
