### ISSUE TITLE
Feature request: separate URLs for search result

### ISSUE THREAD

**Issue by mfioretti** [go-shiori/shiori#111]
preamble: I am **not** sure if this is the most effective way to ask for features or report issues, and apologize in advance if it isn't! I am going to open several issues, however, to keep them well separated    

Here is the issue: when you do a search on some tags, e.g. "#fact checking" #government it works, but the URL in the side bar remains the home one, i.e. http://<servername>:8080/

It would be very useful to have different urls for each search result, i.e. in the case above something like http://localhost:8080/fact checking+government (the actual format doesn't matter, as long as it is unique

those URLs could then be directly used e.g. in websites, if one wanted to say "to know more,please check my bookmarks about [government fact checking]..."

Thanks

**Comment by RadhiFadlillah** [comment]
Hi @mfioretti, sorry for late, late response.

This feature has been implemented per [latest](https://github.com/go-shiori/shiori/commit/d35a396ad203c51829589636909735adab42d431) [commit](https://github.com/go-shiori/shiori/commit/3f43424af0e3f190cc76f7f3928ecfc28ed0889c). Now URL will always unique and changed depending on current page or search keyword that specified by user.

I will close this issue for now, feel free to reopen it if needed.
