### ISSUE TITLE
[PENDING] Portability on Windows

### ISSUE THREAD

**Issue by sergeevabc** [go-shiori/shiori#126]
Dear @RadhiFadlillah, I’m looking for a way to make Shiori truly portable, i.e. to keep database in the same folder where shiori.exe is located, or at least to look for database there first (then fall back to %userprofiles%\AppData\Local\shiori if database is not present in the same folder). How?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by RadhiFadlillah** [comment]
Hi @sergeevabc, sorry for slow response. I've been really busy these week, so I haven't got the time to check issues here.

Unfortunately, right now there is no way to do it, unless you make a change in [code](https://github.com/RadhiFadlillah/shiori/blob/master/path-generator.go#L19) and build it yourself.

**Comment by RadhiFadlillah** [comment]
Now Shiori has `--portable` flag. By using it, Shiori will create `shiori-data` directory in the location of executable file, and use it to store the data.

```
Simple command-line bookmark manager built with Go

Usage:
  shiori [command]

Available Commands:
  add         Bookmark the specified URL
  delete      Delete the saved bookmarks
  export      Export bookmarks into HTML file in Netscape Bookmark format
  help        Help about any command
  import      Import bookmarks from HTML file in Netscape Bookmark format
  open        Open the saved bookmarks
  pocket      Import bookmarks from Pocket's exported HTML file
  print       Print the saved bookmarks
  serve       Serve web interface for managing bookmarks
  update      Update the saved bookmarks

Flags:
  -h, --help       help for shiori
      --portable   run shiori in portable mode
```

With that said, I believe this issue has been fixed now so I will close it. Feel free to reopen it if needed.
