### ISSUE TITLE
Even when a site to try bookmarking is down, I want to add a bookmark

### ISSUE THREAD

**Issue by mzch** [go-shiori/shiori#128]
Hi,

For now when a site to try bookmarking is temporarily down, shiori fails to add a bookmark, reporting Network error. But even then I want to add a bookmark. Can you add an option to toggle its behavior?

**Comment by RadhiFadlillah** [comment]
Since the ramadhan branch is merged, this issue should be fixed now. Therefore, I will close this issue. Feel free to reopen it if the issue still exists.
