### ISSUE TITLE
Feature Request: Search through excerpt + tags

### ISSUE THREAD

**Issue by demlak** [go-shiori/shiori#134]
I just installed shiori for the first time and i'm very excited at the moment.

i tried to search through the bookmarks and, as far as i see, it's not possible to search through the excerpts of websites?

Since those excerpts are often filled with typical information of the site, it would be usefull to search through.

**Comment by RadhiFadlillah** [comment]
Since the ramadhan branch is merged, this feature has been implemented. Therefore, I will close this issue. Feels free to reopen it if the issue still exists.
