### ISSUE TITLE
BUG: Tag Suggestion in edit mode 

### ISSUE THREAD

**Issue by demlak** [go-shiori/shiori#135]
As far as i see, the tag-suggestions do not work in bookmark-edit-mode.
#33

**Comment by RadhiFadlillah** [comment]
Since `ramadhan` branch has been merged, it should be fixed now :

![suggestion-in-edit-mode](https://user-images.githubusercontent.com/6129042/63782709-fe552580-c915-11e9-94bc-6d7fcf0a2ab4.png)

I will close this issue for now, feel free to reopen it if needed.
