### ISSUE TITLE
Feature Request: Global Tag edit

### ISSUE THREAD

**Issue by demlak** [go-shiori/shiori#136]
Would be nice to edit tags. 
sometimes an intention behind a new tag changes later.. or there is a typo in it and it is still wide used.. and it would be nice to re-edit it for all bookmarks.

**Comment by RadhiFadlillah** [comment]
Since the ramadhan branch has been merged, this feature has been implemented :

![rename-tag](https://user-images.githubusercontent.com/6129042/63777495-62bfb700-c90d-11e9-9797-be6fddba2a47.gif)

I will close this issue for now. Feel free to reopen it if needed.
