### ISSUE TITLE
Feature Request: Auto deletion/auto tagging of bookmarks with given date/time

### ISSUE THREAD

**Issue by demlak** [go-shiori/shiori#140]
Sometimes there are bookmarks which will get obsolet on a specific date. for example scheduled events. 
would be nice to have a feature to automaticaly delete those bookmarks.. and/or to filter them out on search, etc.

**Comment by RadhiFadlillah** [comment]
Hi @demlak, sorry for late response. Unfortunately, I don't think I will do it. After testing out, it adds too much complexity to Shiori which make it a pain to maintenance.
