### ISSUE TITLE
Update to master branch

### ISSUE THREAD

**Issue by sascha-andres** [go-shiori/shiori#146]
Hi,
I just wanted to try the version in master. Unfortunately it fails due to missing columns.

How to update the database?

Best,
Sascha

**Comment by RadhiFadlillah** [comment]
Huh, I thought I've made the database backward compatible. Let me check it for a minute.

**Comment by RadhiFadlillah** [comment]
Ahh yeah, I forgot to add `public` column in table `bookmark`. It should be fixed by [89aad30](https://github.com/go-shiori/shiori/commit/89aad30a177a512ef3984699202c26d8c5cd1f89).

**Comment by sascha-andres** [comment]
Worked. Thanks
