### ISSUE TITLE
Failed to build from source using go get command

### ISSUE THREAD

**Issue by insidesmart** [go-shiori/shiori#151]
https://github.com/go-shiori/shiori/blob/a5b4f78f10a9638772724b0d3e2edeacd632c83c/pkg/warc/internal/archiver/processor.go#L13
https://github.com/go-shiori/shiori/blob/a5b4f78f10a9638772724b0d3e2edeacd632c83c/pkg/warc/internal/archiver/processor.go#L14

Apparently 

> github.com/tdewolff/parse/v2/

 doesnt exist and it causes build to fail.

**Comment by RadhiFadlillah** [comment]
That's weird, I've tested it just now and it works properly. My command is :

```
go get -u -v github.com/go-shiori/shiori
```

The `v2` part in `github.com/tdewolff/parse/v2/` is just how Go modules tells that the package is version 2. The `vN` part is exist if the package released with version 2 or higher as explained in [wiki](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

**Comment by insidesmart** [comment]
Strange. I see the following as the result when I deleted the old directory and tried installing via 
*go get -v github.com/go-shiori/shiori*

```
....
github.com/tdewolff/parse (download)
package github.com/tdewolff/parse/v2/css: cannot find package "github.com/tdewolff/parse/v2/css" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/tdewolff/parse/v2/css (from $GOROOT)
....
```

Note: I am trying it in **Mac OS**

**Comment by RadhiFadlillah** [comment]
Have you tried the `-u` flag ?

After you delete the old `shiori` folder and download it again using `go get -v`, it will redownload the Shiori's repository, but not the Shiori's dependencies. Hence why it can't find `tdewolff/parse/v2/` package from `$GOROOT`.

By using `-u` flag, `go get` will also download the dependencies which hopefully fixed this issue.

**Comment by insidesmart** [comment]
It worked after I upgraded go from 1.10 to 1.13. You could close this request. Thanks.
