### ISSUE TITLE
account command gone?

### ISSUE THREAD

**Issue by jmcbee** [go-shiori/shiori#152]
```
$ go get github.com/RadhiFadlillah/shiori
../../go/src/github.com/RadhiFadlillah/shiori/main.go:6:2: use of internal package github.com/go-shiori/shiori/internal/cmd not allowed
```

```
$ cd ~/go/src/github.com/RadhiFadlillah/shiori
$ go install
```

```
$ ~/go/bin/shiori
Simple command-line bookmark manager built with Go

Usage:
  shiori [command]

Available Commands:
  add         Bookmark the specified URL
  delete      Delete the saved bookmarks
  export      Export bookmarks into HTML file in Netscape Bookmark format
  help        Help about any command
  import      Import bookmarks from HTML file in Netscape Bookmark format
  open        Open the saved bookmarks
  pocket      Import bookmarks from Pocket's exported HTML file
  print       Print the saved bookmarks
  serve       Serve web interface for managing bookmarks
  update      Update the saved bookmarks

Flags:
  -h, --help       help for shiori
      --portable   run shiori in portable mode

Use "shiori [command] --help" for more information about a command.
```

**Comment by RadhiFadlillah** [comment]
Yep, now account management is done entirely via web interface. 

To access web interface, run `shiori serve` which by default will run web interface in port `:8080`. In browser, open `http://localhost:8080` (or any other port that you used), then log in using default user:

```
username: shiori
password: gopher
```

In web interface, use setting page to manage accounts:

![Screenshot_2019-09-21 Shiori - Bookmarks Manager](https://user-images.githubusercontent.com/6129042/65363530-a2d93780-dc36-11e9-88d8-5c1bf706655f.png)

**Comment by Chaz6** [comment]
I think it would be useful if there was a cli command to reset passwords.

**Comment by rezart** [comment]
It would also be helpful to place the default credentials in the readme / installation instructions.

**Comment by jmcbee** [comment]
The wiki page was outdated but it looks like you updated it yesterday. Thanks!
