### ISSUE TITLE
Feature request: Using external mysql database

### ISSUE THREAD

**Issue by matusnovak** [go-shiori/shiori#156]
Would it be possible to use an external MySQL database? I have noticed that connecting to the MySQL is done via:

https://github.com/go-shiori/shiori/blob/2eb6415fa883b8c7268a72064bf14c38e46babe9/internal/database/mysql.go#L23

From my understanding, that uses localhost automatically and there is currently no way how to specify hostname. Only username, password, and dbname can be changed via environment variables. 

I would like to use an external database. Would that be possible? The reason is that I am planning to run this in a docker swarm, having persistent volume across nodes is tricky, so having centralised MySQL database would be easy in this case.

**Comment by RadhiFadlillah** [comment]
Hi @matusnovak,

Yeah, the database adress should be changeable via environment variable as well. Will add it ASAP.

**Comment by RadhiFadlillah** [comment]
@matusnovak per [df98c28](https://github.com/go-shiori/shiori/commit/df98c281d3d742f83e21d11b0eb0d50b6366173b) I've made the database address changeable via environment variable `SHIORI_MYSQL_ADDRESS` https://github.com/go-shiori/shiori/blob/df98c281d3d742f83e21d11b0eb0d50b6366173b/internal/cmd/root.go#L105-L113

**Comment by matusnovak** [comment]
Awesome! Thank you very much.

**Comment by matusnovak** [comment]
For future visitors:

If anyone is trying to do the same, you have to wrap the MySQL address in `tcp(...)` as the following:

```
docker run ... -e "SHIORI_MYSQL_ADDRESS=tcp(mysql_address_or_ip_here:3306)"
```

Reference: https://github.com/go-sql-driver/mysql/issues/427
