### ISSUE TITLE
Doesn't always grab images

### ISSUE THREAD

**Issue by danmed** [go-shiori/shiori#160]
I'm just testing this and the archive feature doesn't appear to always grab images...

For example, when archiving the below link, none of the images are captured in the archive, but a thumbnail is generated.

https://imgur.com/a/W5wZxHT

I'm running the docker image btw..

**Comment by RadhiFadlillah** [comment]
@danmed yep, unfortunately the archival still doesn't work properly with page that uses a lot of Javascript like imgur and Reddit (the old Reddit is fine though), and unfortunately I don't have any idea where to start to solve this.

**Comment by danmed** [comment]
Ah ok, will it still does a pretty good job.. so thank you..

**Comment by deanishe** [comment]
> and unfortunately I don't have any idea where to start to solve this.

I was thinking about something like a set of URL rewriting rules, which might help Shiori handle certain sites (like Reddit). For example, a rule might rewrite `www.reddit.com/...` to `old.reddit.com/...` to get a more easily parseable version of a page.

For other sites, the mobile or print version (if they exist) might be much easier to parse.

For example, Shiori does a good job with [this article from the Spiegel](https://www.spiegel.de/wirtschaft/unternehmen/thomas-cook-gegen-tui-das-duell-der-reisekonzerne-ist-entschieden-a-1288236.html), but it also grabs a bunch of the dumb user comments that aren't in [the print version](https://www.spiegel.de/wirtschaft/unternehmen/thomas-cook-gegen-tui-das-duell-der-reisekonzerne-ist-entschieden-a-1288236-druck.html).

**Comment by linwaytin** [comment]
I also have the same problem.
I think there are two possible ways to deal with this problem.

First, let users enter the link manually.
Second, as @deanishe mentioned, rules can help Shiori to determine where the image is.

At least, I like to be able to enter the link manually.
For now, if the image is not correct, there is nothing I can do to fix it.

Anyway, thank you for this great project.

**Comment by fmartingr** [comment]
This will get worked on with #353. After the switch, we can start fixing this kind of things directly on [obelisk](https://github.com/go-shiori/obelisk).
