### ISSUE TITLE
ubuntu 18 compatibility?

### ISSUE THREAD

**Issue by sigmonsays** [go-shiori/shiori#165]
<pre>
sig@desktop2:~/Downloads$ ./shiori-linux-amd64 
./shiori-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./shiori-linux-amd64)

sig@desktop2:~/Downloads$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

sig@desktop2:~/Downloads$ file $(which ls)
/bin/ls: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=9567f9a28e66f4d7ec4baf31cfbf68d0410f0ae6, stripped
</pre>

**Comment by deanishe** [comment]
I had the same issue on Stretch. It works fine if you build it yourself.

**Comment by RadhiFadlillah** [comment]
Yeah, this is the problem when building Linux binary from distro with rolling release like Manjaro. I will use Ubuntu VM to replace it ASAP.

**Comment by RadhiFadlillah** [comment]
Could you check the [`shiori-linux-amd64-buster`](https://github.com/go-shiori/shiori/releases/download/v1.5.0/shiori-linux-amd64-buster) in release page ? I've build it using Debian buster which hopefully fixed this issue.

**Comment by shyim** [comment]
I have the same with both binaries.

**Comment by sigmonsays** [comment]
Thanks for the cool project.

shiori-linux-amd64-buster shows the same issue on ubuntu 18. 

I think travis is a good idea. It might be worth building in a docker for the target platform if you want more control. Here is an example script I put together. Let me know if you want it in a PR

Create the build script, buildit
<pre>
#!/bin/bash
set -x
export GOPATH=/go
apt-get update
apt-get install -y git wget gcc
mkdir -p /usr/local
cd /usr/local
wget -O go.tar.gz https://dl.google.com/go/go1.13.linux-amd64.tar.gz
tar zxf go.tar.gz
export PATH="$PATH:/usr/local/go/bin"
go get github.com/go-shiori/shiori
cp -v $GOPATH/bin/* /target

</pre>

then build it
<pre>
rm -rf build
mkdir build
docker run --rm -v $(pwd)/build:/target -v $(pwd)/buildit:/build ubuntu:bionic /build
</pre>

**Comment by RadhiFadlillah** [comment]
@sigmonsays sorry, now Ubuntu 18.04 should be supported by [`shiori-linux-amd64-stretch`](https://github.com/go-shiori/shiori/releases/download/v1.5.0/shiori-linux-amd64-stretch) in release page. It seems Ubuntu 18.04 still use GLIBC 2.27 while Buster and Manjaro is 2.28 alreay. Fortunately Debian Stretch still in 2.24, so I used that one.

For Travis I don't think I want to use it for now. There are still no unit test yet, and the release for Shiori is still not that often so IMHO it's better for me to build it manually.

**Comment by RadhiFadlillah** [comment]
Since it seems fixed now, I'll close this issue. Feel free to reopen it if needed.
