### ISSUE TITLE
Display as table/list - without thumbnails?

### ISSUE THREAD

**Issue by ekianjo** [go-shiori/shiori#166]
In the interest of information density, can you provide another "display as list" option where no thumbnails are shown at all? I believe you could also have this kind of "view change" icon directly in the interface rather than in the settings.

**Comment by RadhiFadlillah** [comment]
@ekianjo I've implemented it in [bccc70b](https://github.com/go-shiori/shiori/commit/bccc70b3f8525a662d0725443ac1ab5065142a95). Now in settings there is option to hide thumbnail image:

![New option](https://user-images.githubusercontent.com/6129042/65477487-a972e380-deb0-11e9-88a9-7e4f4d95238d.png)

When used, all thumbnail will be gone and replaced with excerpt (if the excerpt exists) :

![No thumbnail](https://user-images.githubusercontent.com/6129042/65477521-c5768500-deb0-11e9-89d0-95b3bb8841d0.png)

The same will also happened in list mode :

![No thumbnail, list mode](https://user-images.githubusercontent.com/6129042/65477562-e17a2680-deb0-11e9-8a72-342e80373931.png)

IMHO it's a bit too busy when used in mobile, but maybe it's nice for people that prefer information density :

![Screenshot_2019-09-24 Shiori - Bookmarks Manager(3)](https://user-images.githubusercontent.com/6129042/65477616-0c647a80-deb1-11e9-808b-db25a00920a3.png)

**Comment by ekianjo** [comment]
Nice! Can I make another suggestion? For the list mode my intention was to only show the title and the tags and nothing else (no excepts either). Maybe you could apply that by having an option to show/hide excerpts ?

**Comment by RadhiFadlillah** [comment]
@ekianjo it's done in [a82b882](https://github.com/go-shiori/shiori/commit/a82b8820bd34ab3611f304c1a84b05a96adce5c3). Now in settings there is option to hide excerpt:

![Options page](https://user-images.githubusercontent.com/6129042/65523613-b9251300-df16-11e9-83d3-d57aefdb7610.png)

![No excerpt](https://user-images.githubusercontent.com/6129042/65523659-c9d58900-df16-11e9-912b-4035cb362777.png)

![No excerpt, mobile](https://user-images.githubusercontent.com/6129042/65523832-0a350700-df17-11e9-9296-f66162afb827.png)

**Comment by ekianjo** [comment]
Wow this is great! Thanks a lot! When do you plan to merge this on Master?

**Comment by RadhiFadlillah** [comment]
@ekianjo it's already in master actually. Unfortunately, there are no prebuilt binary yet so you have to build it from source by yourself:

```
go get -u -v github.com/go-shiori/shiori
```

**Comment by ekianjo** [comment]
Got it! What is your release policy for binaries? Do you have a schedule or do you follow milestones?

**Comment by RadhiFadlillah** [comment]
@ekianjo I don't have any release policy yet, I just release when I think the new version has improved exponentially from before.

**Comment by ekianjo** [comment]
Thanks - very clear! @RadhiFadlillah since you have completed that task I will close this issue.
