### ISSUE TITLE
Missing documentation about using mysql

### ISSUE THREAD

**Issue by ReekyMarko** [go-shiori/shiori#168]
I have looked through the wiki and the help pages within shiori, and I can't find anything on how to use mysql. I can add this to the wiki myself if someone explains to me how I can use it.

**Comment by RadhiFadlillah** [comment]
@ReekyMarko sorry I forgot to add it to the wiki.

To use MySQL database, first set environment variable `SHIORI_DBMS` to `mysql`. After that specify the user, password database name (and if needed the address of database) via these environment variables :

- `SHIORI_MYSQL_USER`
- `SHIORI_MYSQL_PASS`
- `SHIORI_MYSQL_NAME`
- `SHIORI_MYSQL_ADDRESS`

In Linux this can be done in one command like this :

```
env SHIORI_DBMS=mysql \
    SHIORI_MYSQL_USER=radhi \
    SHIORI_MYSQL_PASS=password \
shiori serve
```

The related code for these actions can be seen here : https://github.com/go-shiori/shiori/blob/df98c281d3d742f83e21d11b0eb0d50b6366173b/internal/cmd/root.go#L103-L118

By the way, if you use `SHIORI_MYSQL_ADDRESS`, the address must be wrapped in the protocol e.g. `SHIORI_MYSQL_ADDRESS=tcp(mysql_address_or_ip_here:3306)`. For more details check issue #156.

**Comment by ReekyMarko** [comment]
Thanks a lot! I think this is already sufficient to add to the wiki
