### ISSUE TITLE
Search function clarification

### ISSUE THREAD

**Issue by ekianjo** [go-shiori/shiori#173]
Hi, I would like to know what is actually searched when searching in shiori? 
Does it crawl titles only? or titles + tags ? or titles + tags + excerpts ? or titles + tags + excepts + cached content?

**Comment by RadhiFadlillah** [comment]
Shiori will search the keyword in URL, title, excerpts and cached content, as can be seen here : https://github.com/go-shiori/shiori/blob/89aad30a177a512ef3984699202c26d8c5cd1f89/internal/database/sqlite.go#L238-L250

If you include or exclude a tag, then it will lookup on the tags as well.

**Comment by ekianjo** [comment]
sorry it's not clear for me, how do you include or exclude a tag when doing the search?

**Comment by RadhiFadlillah** [comment]
In command line interface, from `print` command you can use `-t` flag to include tags and `-e` flag to exclude tags. In web interface, in search bar use `tag:tagname` to include tags and `-tag:tagname` to exclude tags. 

In web interface you can also use tags dialog. To include tags just click on the tag name you want to include, and to exclude use Alt + Click on the tag name that you want to exclude.

**Comment by 8bitgentleman** [comment]
2 questions

1. Is there and API endpoint to search shiori?
2. Is there a documentation page for tidbits like adding tag:tagname or is it just in the code for now?

**Comment by RadhiFadlillah** [comment]
@8bitgentleman 

> Is there an API endpoint to search shiori?

Yeah, there is. First you need to login via `POST /api/login`. It accepts JSON object like this :

```
{
  "username": "shiori"      // The username
  "password": "gopher",     // The password
  "remember": 5,            // How long session is, negative means session won't expired
  "owner": true,            // Specify that this login is for owner
}
```

It will returns the session ID and logged in account data like this :

```
{
    session: some-random-uuid-v4-key,
    account: {
        username: shiori,
        owner: true
    }
}
```

Now we can use endpoint `GET /api/bookmarks`. It accepts several URL queries:

```
keyword : keyword that want to be searched
tags    : tags that want to be included
exclude : tags that want to be excluded
page    : page number, default 1
```

To access the endpoint, attach the session ID as `X-Session-ID` header and send the request. For example, you want to get bookmarks in page 1 :

```
curl 'http://localhost:8080/api/bookmarks?page=1' \
    -H 'X-Session-ID: session-id'
```

To get bookmarks which contain keyword "interview" :

```
curl 'http://localhost:9000/api/bookmarks?keyword=interview' \
    -H 'X-Session-ID: session-id'
```

**Comment by 8bitgentleman** [comment]
Wow this is great, thanks for the quick reply!

**Comment by ekianjo** [comment]
@RadhiFadlillah for the wiki why don't you create issues as to what needs to be better documented, and then the community can help so you don't have to do everything by yourself?

**Comment by matclab** [comment]
I've added some documentation to the Usage page… 
It may be enough to close this issue.

**Comment by RadhiFadlillah** [comment]
@ekianjo sure I will create new issue for that later.

@matclab thanks, closing this issue now.
