### ISSUE TITLE
Add a "read later" option when adding a bookmark

### ISSUE THREAD

**Issue by ekianjo** [go-shiori/shiori#178]
Not sure about the UI yet, but I think it would be ready useful to have a simple box to tick when you add a bookmark to differentiate between the bookmarks you have read and want to keep, and the bookmarks you are adding because you want to check them out later. 

What do you think?

**Comment by 8bitgentleman** [comment]
Sounds similar to the Archive feature that Pocket has. Pocket's feature is a bit more robust (obviously). You can archive items, which removes them from the main list of bookmarks to an "Archived" list.

**Comment by fmartingr** [comment]
Moving this discussion here: https://github.com/go-shiori/shiori/discussions/343
