### ISSUE TITLE
Can't find the bookmarklet

### ISSUE THREAD

**Issue by 8bitgentleman** [go-shiori/shiori#180]
The last issue I see about finding the bookmarklet is #100 . Since then the UI has changed and the about screen is no longer shown. Where is the bookmarklet now or has it been superseded by the chrome extension?

**Comment by RadhiFadlillah** [comment]
Yeah, it has been dropped in favor of web extension. Unfortunately, for now it only tested in Firefox, so I'm not sure it will works in Chrome.

**Comment by 8bitgentleman** [comment]
Ok that makes sense, thanks

**Comment by timshannon** [comment]
The extension does not seem to work in chrome, and there is an outstanding issue in the extension repository to add chrome support.  

Do you have a work around for anyone on chrome?  Can you copy and past an example bookmarklet here?

**Comment by 8bitgentleman** [comment]
I loaded it up yesterday in chrome and it works just fine

**Comment by timshannon** [comment]
Hm, so it looks like you can install the extracted zip in developer mode in chrome, but you'll always get warnings:

https://stackoverflow.com/questions/24577024/install-chrome-extension-not-in-the-store

Is that what you're doing @8bitgentleman?

I'm not sure why all of the complications of an extension is needed.  It'd be nice to have a bookmarklet fallback that simply passes in the URL and page title to the add link dialog.  I haven't looked too much through the code, but it looks like that's not possibly.

I could write a bookmarklet to make the POST call, but I'd run into issues with CORs.

**Comment by dav-m85** [comment]
@timshannon same here, installing the extension in dev mode, no warnings in MacOSX.

@RadhiFadlillah is there an official extension on the chrome store ? if needed, I have paid the fee to get an account myself, I could host it.

**Comment by 8bitgentleman** [comment]
> Hm, so it looks like you can install the extracted zip in developer mode in chrome, but you'll always get warnings:

Yup, I"m in developer mode and don't get the warning you mention. I think the benefit of the extension is being able to add tags directly to the bookmark when it's saved

**Comment by brettinternet** [comment]
@RadhiFadlillah I didn't realize the bookmarklet support had been dropped. Since extensions aren't supported on mobile browsers, there is now no mobile support.

**Comment by 8bitgentleman** [comment]
Do bookmarklets even work on mobile?

**Comment by brettinternet** [comment]
Yes, but I've only tested on iOS Safari and Firefox.
