### ISSUE TITLE
Putting shiori behind a path via a reverse proxy

### ISSUE THREAD

**Issue by rare-energy** [go-shiori/shiori#181]
I want to put shiori behind a reverse proxy such that I can reach it at `https://example.com/path/shiori/`, however shiori's frontend does not like this.

I am able to use the shiori Firefox extension and am able to authenticate with the API at the following host URL: `https://example.com/path/shiori`.

However when I try to visit that URL with a browser, I am redirected to `https://example.com/login` instead of `https://example.com/path/shiori/login`.

Is there a way to provide a base URL to shiori?

**Comment by RadhiFadlillah** [comment]
Hi @rare-energy, this is one of Shiori's oldest issue (#39) that I haven't fixed yet. Fortunately, I'm almost done with it so hopefully it will be fixed in following weeks.

With that said, since this issue is already tracked I will close this one.

**Comment by rare-energy** [comment]
Ah, must have missed that issue. Glad to see that it will be fixed. Thanks for your work on Shiori!

**Comment by rogerBridge** [comment]
Hello sir, 
```environment
debian 10 + docker 19.03.12
docker image version: latest, image ID: 69e24681b088
```
I face the same issue when I set a reverse proxy, I set the url is: https://mydomain.me/shiori/, but when I visit https://mydomain.me/shiri/ , I am be redirect to https://mydomain.me/login?dst=%2F, and this page show nothing, could anybody help me? thanks 🤣
