### ISSUE TITLE
Firefox 56 support

### ISSUE THREAD

**Issue by demlak** [go-shiori/shiori#183]
I don't know what exactly is the reason for, but Firefox 56 does not work with shiori 1.5.

Maybe this is because of vue.js?

We get error on login page (with rotating dots left of "LOG IN":
![Screenshot_20190927_214741](https://user-images.githubusercontent.com/11285006/65797894-9e4ddb00-e170-11e9-919e-af087c854ae6.png)

i know that ff56 is outdated and is not supported anymore by mozilla. But there are MANY people outthere using it because of old plugin/addons.

**Comment by RadhiFadlillah** [comment]
Hi @demlak,

Unfortunately, I don't think I could do this. That error is happened because FF56 doesn't support ES6 module which only [supported](https://caniuse.com/#feat=es6-module) since FF60. And I'm not sure I would go back working in JS without module.
