### ISSUE TITLE
Select issues for Hacktoberfest 🎆!

### ISSUE THREAD

**Issue by dav-m85** [go-shiori/shiori#191]
@RadhiFadlillah Hi, just in case you missed it, there's the [hacktoberfest](https://hacktoberfest.digitalocean.com/details) going on. I would like to help the project but don't know which issues would make the more bang for my time.

Apply the "Hacktoberfest" label on the ones you need would help me (and maybe some fellow devs) to push the repo forward. Thanks !

**Comment by RadhiFadlillah** [comment]
Yeah, that sounds great.

I will need to create contributing guide first though, so it might take a while :bowing_man:

**Comment by dav-m85** [comment]
Hacktoberfest's over, closing this :)
