### ISSUE TITLE
Unable to login on macos

### ISSUE THREAD

**Issue by fnino** [go-shiori/shiori#194]
I downloaded latest release of shiori, latest golang compiler, and installed it natively on macos 10.13.  Runs on commandline ok: can add, print, and serve.  sqlite db is created ok.  However, despite using the default login and passwork, i cannot get past the login screen on the webserver.  Line 78 in handler-api.go gets executed alright, but no session is opened...

**Comment by fnino** [comment]
Did the same on a linux box and it works ok....!

**Comment by RadhiFadlillah** [comment]
Hi @fnino

Unfortunately, I don't have any MacOS machine to test it. Are there any error message in terminal or in web console ? And what is your browser ?

Thank you.

**Comment by StefanCohen** [comment]
I don't know if it is related but the latest release prevents me from logging in with my regular username/password on OSX. Credentials are coming from Keychain, so no typos.

**Comment by nfam** [comment]
@RadhiFadlillah on macOS, it works on Firefox but does not on Safari. I debugged and found the issue at
```js
document.cookie = `session-id=${json.session}; Path=${document.baseURI}; Expires=${expTime}`;
```
I replaced `${document.baseURI}` with `/`, and it worked.

Therefore, the problem should be: `Path` on Safari must a valid path (starting with `/` in URI spec); but `document.baseURI` is not since it starts with scheme and host.

**Comment by RadhiFadlillah** [comment]
Thanks @nfam :+1: 

@fnino could you check it out again ?

**Comment by fnino** [comment]
Yes !  It works!! Thanks !

  Fernando

On Fri, Oct 11, 2019 at 07:17:16AM +0000, Radhi wrote:
>Thanks @nfam :+1:
>
>@fnino could you check it out again ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/go-shiori/shiori/issues/194#issuecomment-540945240

-- 
___________________________________________________________________________________________
Fernando NIÑO
LEGOS (UMR5566 CNES/CNRS/IRD/UPS)                                     18, Av. Edouard Belin
Tél: 05.61.33.47.38                                                  31401 Toulouse Cedex 9
