### ISSUE TITLE
feature suggestion : URL shortener

### ISSUE THREAD

**Issue by starfish1337** [go-shiori/shiori#195]
I know that shiori is meant to be a "simple clone of Pocket", but adding a URL shortener as a feature would be amazing. 

People who use separate self hosted apps for URL shorteners, can then consolidate to this one app.

**Comment by RadhiFadlillah** [comment]
Hi @starfish1337, sorry for late response. Unfortunately, I don't think I will implement this.

IMHO it's out of scope of Shiori's purpose. Not to mention it's quite hard to do, so I'm not sure I've got the time to implement and maintain it.
