### ISSUE TITLE
Freebsd Support using go releaser

### ISSUE THREAD

**Issue by jakeswenson** [go-shiori/shiori#196]
My home server is a freebsd server, and I'd love to run this on it. You should be able use [go releaser](https://goreleaser.com/introduction/) to make builds easier

**Comment by deanishe** [comment]
> You should be able use go releaser to make builds easier

Unfortunately not.

Shiori uses SQLite, which requires cgo, and [GoReleaser doesn't support cgo](https://goreleaser.com/limitations/cgo/).
