### ISSUE TITLE
mobile applications

### ISSUE THREAD

**Issue by Nover2** [go-shiori/shiori#198]
Will Shiori support mobile applications in the future? Such as iOS and Android. So that we can save bookmarks to Shiori via other apps instead of adding bookmarks in the website manually. And we can review bookmarks quickly.

**Comment by RadhiFadlillah** [comment]
Hi @Nover2, sorry for late response.

Unfortunately I don't think I will do this. Building mobile application IMHO is too hard and require too much time investment, especially considering I only working on Shiori in my free time. Not to mention the mobile app will bring its own set of bugs :tired_face:
