### ISSUE TITLE
Bookmark content displays Invalid Date if database is PostgreSQL

### ISSUE THREAD

**Issue by nfam** [go-shiori/shiori#201]
<img width="862" alt="Screenshot 2019-10-12 at 7 29 35 PM" src="https://user-images.githubusercontent.com/35899503/66701783-7f337980-ed2a-11e9-863f-531741d87383.png">

As seen on the above screenshot, the `modified` has suffix `Z` which indicates `UTC` timezone. So adding `+00:00` will make the time string invalid.

**Comment by RadhiFadlillah** [comment]
Since the fix has been merged, I will close this issue.
