### ISSUE TITLE
Archives getting created with setting "Create archive by default" turned off

### ISSUE THREAD

**Issue by mserajnik** [go-shiori/shiori#203]
First of all, thank you for this project, I find it very neat.

The issue I've run into though is that I have `Create archive by default` ticked off in the settings but Shiori still creates archives for certain pages (e.g., Reddit).

This takes time when adding the bookmark and also isn't perfect in many cases. E.g., Reddit's new design is heavily reliant on JS, so Shiori doesn't grab the comments (as they are loaded via XHR). This makes it more annoying than useful to me when it happens by default.

Is there no way to completely disable archive creation until manually triggered?

And while on the topic, once an archive has been created, is there a way to delete it again (via the web interface)? I couldn't find that option.

Thank you!

**Comment by RadhiFadlillah** [comment]
Hi @mserajnik,

> The issue I've run into though is that I have Create archive by default ticked off in the settings but Shiori still creates archives.

Yep, I've made a mistake where checkbox is ignored in all dialog. It should be fixed by [7d938f3](https://github.com/go-shiori/shiori/commit/7d938f38930164a61274012427129bcead0288ec). Could you try it again ?

> And while on the topic, once an archive has been created, is there a way to delete it again (via the web interface)? I couldn't find that option.

No, unfortunately right now there is no option to do that yet.

**Comment by mserajnik** [comment]
Thank you, I gave this a try yesterday, this seems to be fixed now. :)

**Comment by mserajnik** [comment]
Sorry, need to reopen this. While the issue didn't come up again on the same test links I had tried before, it still seems to occur for certain sites/pages.

E.g., when bookmarking [`https://projectimmersion.com/`](https://projectimmersion.com/), it still always adds the archive, regardless of the setting.

My best bet would be that text length seems to be a factor that decides if a page gets archived automatically even with the setting off or not; at least it seemed like this from the pages I've tried.

**Comment by mserajnik** [comment]
After looking into this again, I figured out that this is not a bug, merely a misunderstanding on my side.

I didn't know the difference between the _saved content_ and the _archive_. Shiori seems to always store a plain text version of a bookmark if it can (the requirement probably being that there is actual text content => it won't work with SPA's where there is only JS served).

The archive then is an expanded version of that where it will save the whole page including assets (styles, images).

Keeping that in mind, the archive flag works as intended and this can be closed. I will open a different issue with a feature request to either (optionally) turn off the stored content or change how the bookmark is linked so it prefers the original URL.
