### ISSUE TITLE
Page content disappears 

### ISSUE THREAD

**Issue by gerroon** [go-shiori/shiori#207]
Hi

I used Shiori to capture this page. When I click on it in Shiori, page opens blank, but there seems to be a milisecond prior to reloading page fully when the page content is shown but it disappears very quickly.

I tried it on FF on Linux and Android.

https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/matrices

**Comment by fmartingr** [comment]
Hey @gerroon I've tried this on mac and linux firefox and it captures and works well (content does not dissapear and is not a blank page). I'm going to close it but if issue is still happening please comment so we can investigate further.

![Screenshot 2022-02-06 at 16 49 36](https://user-images.githubusercontent.com/812088/152689023-ab455992-db4f-4efb-be9e-6c7207643059.png)
