### ISSUE TITLE
How to setup PostgreSQL with Heroku?

### ISSUE THREAD

**Issue by m-rio** [go-shiori/shiori#212]
Hi, used the heroku deploy button to try shiori (great work, btw!) and it work seamlesly. The only issue is that by default I believe this is storing the links in heroku's ephemeral filesystem which means that they disappear within 24h.

Reading the wiki I realized I can store the link in postgresql, so I provisioned a free heroku postgresql db but I'm not sure how I should configure shiori to use it.

Here's the credential info I got from db:
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/41305636/68596868-b6f12680-047a-11ea-9279-12c6ffd4c87c.png">

also, by default heroku sets up this variable for the db:
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/41305636/68596935-d2f4c800-047a-11ea-8edd-e7fefb032a50.png">

**Comment by elsurudo** [comment]
You can follow the directions here: https://github.com/go-shiori/shiori/wiki/Configuration#postgresql

And deduce all these variables from the `DATABASE_URL` from the image you have posted. I tried this, and it worked for me. Once the ENV vars are set, it will use Postgres.

**Comment by deanishe** [comment]
Closing: appears to be answered.
