### ISSUE TITLE
json: cannot unmarshal bool into Go struct field .remember of type int

### ISSUE THREAD

**Issue by eryajf** [go-shiori/shiori#213]
When I finished deploying and logged in to the Chrome extension, I reported the error

```
json: cannot unmarshal bool into Go struct field .remember of type int
```

**Comment by daledali** [comment]
Same here

**Comment by fmartingr** [comment]
This has happened to me using the API, it's probably a bug in the extension sending the incorrect type in the payload but it will require more work as I'm not sure the current state of the extension and I don't use a firefox compatible browser.

**Comment by fmartingr** [comment]
#346 and #437 modified this logic, and I've just tried with the latest extension version and login works. Can you check it on your side? If you are still experiencing the error we can reopen this issue.
