### ISSUE TITLE
use postgresql and same bookmark with 2 or more tags an error will throw.

### ISSUE THREAD

**Issue by EINDEX** [go-shiori/shiori#216]
When use postgresql and same bookmark with 2 or more tags
And the second time select tag by name 

https://github.com/go-shiori/shiori/blob/9ba9d1eced3417c96402bec1b3310a9e8629c6a3/internal/database/pg.go#L179

Then postgresql will throw error 
"pq: current transaction is aborted, commands ignored until end of transaction block"

**Comment by watson387** [comment]
Same as [215](https://github.com/go-shiori/shiori/issues/215)
