### ISSUE TITLE
Name clash with Shiori.app

### ISSUE THREAD

**Issue by Weltraumschaf** [go-shiori/shiori#220]
Does this project has anything to do with https://aki-null.net/shiori/?

**Comment by dhda** [comment]
It seems unrelated except that they both are tools for working with bookmarks. I almost installed this thing while searching for the original Shiori's browser extension, and thought it might be an updated or open sourced version... but it's not.

**Comment by deanishe** [comment]
Entirely unrelated. Just an odd coincidence, I think. I don't envisage changing the name of this project, though.
