### ISSUE TITLE
Windows - Failed to load module script

### ISSUE THREAD

**Issue by lalitkale** [go-shiori/shiori#226]
I am facing issue #182 again. I downloaded the binary "shiori-windows-amd64.exe" for v1.5.0 on Windows 10 and just fired "shiori serve" and getting blank page with 
`Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec` error in browser console for 'base.js', 'home.js', 'settings.js' and 'dialog.js'.
go version go1.13.5 windows/amd64

Appreciate any help towards workarounds or proper fix.

_Originally posted by @lalitkale in https://github.com/go-shiori/shiori/issues/182#issuecomment-568461097_

**Comment by deanishe** [comment]
Can you please post more information? The version of Windows you're using doesn't help much because it's a browser issue.

Please tell me the browser and version you're using, and if possible the request and response headers from its inspector.

**Comment by lalitkale** [comment]
Thank you so much for responding on the issue. I had been using chrome at the time of reporting the issue. Give me a day or two and I will try to reproduce the issue again with new version. If I still get it, will report it. If not, we can close it. Will that work?

**Comment by sjbr** [comment]
I have this problem on Windows 10 using Chrome or Firefox

**Comment by sjbr** [comment]
The serve command in windows is not configuring properly the MIME types of js scripts.

![image](https://user-images.githubusercontent.com/864919/90093269-70ba4380-dce8-11ea-90c0-39f10f3cc1f8.png)

**Comment by symgryph** [comment]
You might want to try the docker image. You’ll need to use the pull request since the one in master doesn’t compile correctly.

**Comment by lalitkale** [comment]
It looks like, I am not getting enough time to reproduce the issue again. Hence, we could close the issue.

**Comment by 70B43r** [comment]
Stumbled over the same issue. 

After some investigation the following hint leads me to the solution:
https://stackoverflow.com/questions/3442607/mime-types-in-the-windows-registry

Changing "ContentType" of Key HKEY_CLASSES_ROOT\.js to "application/javascript" solved the problem and go serves not the correct mime.

[mimetype.zip](https://github.com/go-shiori/shiori/files/5444115/mimetype.zip)
