### ISSUE TITLE
Disable default account?

### ISSUE THREAD

**Issue by raghur** [go-shiori/shiori#228]
So - this should be a simple thing - but I'm unable to find anything either in the issues or on the wiki.

I've installed Shiori on  a public url, logged in with default creds and added an account. Now I'd like to disable logon(or change default creds) for the default account so that random stranger who ends up on my website can't get in. How do I do this? 

Thanks!

**Comment by vfauth** [comment]
When you create a new 'owner' account, the default account is disabled. I added that to the FAQ in the wiki.

**Comment by raghur** [comment]
Thanks!
