### ISSUE TITLE
Feature request: add the ability to stay logged in for longer periods

### ISSUE THREAD

**Issue by imtbl** [go-shiori/shiori#229]
The _Remember me_ checkbox currently causes the session cookie to expire (and therefore a logout) [after 12 hours](https://github.com/go-shiori/shiori/blob/599afeaae06990f5d13e453ca8461d8cb810718e/internal/view/login.html#L86), which can be quite annoying on private machines.

Please consider adding either an additional checkbox to stay logged in for longer periods (30 days? 90 days? a year even?) or consider adjusting the behavior of the existing one.

I think most people wouldn't expect to get logged out after just 12 hours after ticking a checkbox that says _Remember me_. On most sites this would at least mean several days, but usually around a month I'd think.

**Comment by deanishe** [comment]
Agree. I think I changed my fork to 30 days. I'll increase the session expiry significantly, though as sessions are only stored in RAM, you'll still have to log in again after a restart.
