### ISSUE TITLE
Low-res images for sites that use progressive enhancement?

### ISSUE THREAD

**Issue by neezer** [go-shiori/shiori#230]
I just tried adding a bookmark for a Medium article and noticed the images were imported into Shiori at an atrocious quality:

<img width="1071" alt="Screen Shot 2020-01-20 at 8 58 11 PM" src="https://user-images.githubusercontent.com/29997/72776876-83dcb900-3bc8-11ea-91cf-a5e1c35efb61.png">

I'm guessing this is because Medium will lazy-load the higher-resolution copies with JS, but the Shiori importer doesn't wait around for that. That's my best guess anyways. Inspecting the Medium page source, I see that the images have a `noscript` tag near 'em with he full-quality version of the image... perhaps that could be useful when importing?

Think this is fixable?

**Comment by neezer** [comment]
This was the article I was importing, if it's helpful for testing: https://medium.com/voodoo-engineering/node-js-and-cpu-profiling-on-production-in-real-time-without-downtime-d6e62af173e2

**Comment by neezer** [comment]
Definitely two different URLs:

```diff
- https://miro.medium.com/max/60/1*87KlGgfbuWP38nAaQaj3xw.png?q=20
+ https://miro.medium.com/max/1860/1*87KlGgfbuWP38nAaQaj3xw.png
```

The former is the URL Shiori pulls; the latter is the URL in the fully-loaded Medium article, and also the URL found in the adjacent `noscript` tags. In my testing, the second URL parameter is the deciding factor; the query parameter `q` does not seem to make a significant change, and is missing entirely when the page fully loads and the JS executes on a given image.

This problem is further compounded if you have attempted to Archive the page in Shiori; at present the images don't load at all:

<img width="1103" alt="Screen Shot 2020-01-20 at 9 23 57 PM" src="https://user-images.githubusercontent.com/29997/72777738-8856a100-3bcb-11ea-82af-fb920845e360.png">

---

Seems like this would work fine if Shiori pulled the `noscript` value instead of the given `img` value, but I'm unsure if that's safe/wise to do categorically.

Right now I'm contemplating manually massaging the imported HTML in SQLite to the correct URLs, but that's obviously pretty labor intensive and not something I'd like to do routinely. However, I've also noticed the embedded code examples didn't import at all, so I might have to do that anyways, as I want to have those archived too.

**Comment by 8bitgentleman** [comment]
I would also love to see a fix for medium articles, as that's one of the more common sites I use

**Comment by RadhiFadlillah** [comment]
@neezer @8bitgentleman sorry for late reply.

Just want to tell you the fix for this issue has been implemented in [`go-readability`](https://github.com/go-shiori/go-readability/commit/b2fb1ff01cbe3205872b76477f624abd49dca49a). 

However, it might take a while to merge it to Shiori because I also want to improve the archival method to make it better, at least to make Shiori able to archive pages from Github and its gist.

**Comment by fmartingr** [comment]
Hey everyone, I've tested this and it's currently working on the latest version:

![Screenshot 2022-02-06 at 17 05 25](https://user-images.githubusercontent.com/812088/152689706-e72a5e5a-fcf8-4aaf-ac6b-b6cb564aa2c6.png)

I'm closing this as solved, but if you have any other issues please comment again so we can reopen.

**Comment by rundx** [comment]
> Definitely two different URLs:
> 
> ```diff
> - https://miro.medium.com/max/60/1*87KlGgfbuWP38nAaQaj3xw.png?q=20
> + https://miro.medium.com/max/1860/1*87KlGgfbuWP38nAaQaj3xw.png
> ```
> 
> The former is the URL Shiori pulls; the latter is the URL in the fully-loaded Medium article, and also the URL found in the adjacent `noscript` tags. In my testing, the second URL parameter is the deciding factor; the query parameter `q` does not seem to make a significant change, and is missing entirely when the page fully loads and the JS executes on a given image.
> 
> This problem is further compounded if you have attempted to Archive the page in Shiori; at present the images don't load at all:
> 
> <img alt="Screen Shot 2020-01-20 at 9 23 57 PM" width="1103" src="https://user-images.githubusercontent.com/29997/72777738-8856a100-3bcb-11ea-82af-fb920845e360.png">
> 
> Seems like this would work fine if Shiori pulled the `noscript` value instead of the given `img` value, but I'm unsure if that's safe/wise to do categorically.
> 
> Right now I'm contemplating manually massaging the imported HTML in SQLite to the correct URLs, but that's obviously pretty labor intensive and not something I'd like to do routinely. However, I've also noticed the embedded code examples didn't import at all, so I might have to do that anyways, as I want to have those archived too.

This is still an issue when loading archived version of meduim articles

**Comment by fmartingr** [comment]
> This is still an issue when loading archived version of medium articles

Have you tried updating the cache and see if the new achived version has been correctly downloaded?

**Comment by rundx** [comment]
> > This is still an issue when loading archived version of medium articles
> 
> Have you tried updating the cache and see if the new achived version has been correctly downloaded?

Yes, still the same

<img width="796" alt="Screen Shot 2022-02-26 at 12 35 52 PM" src="https://user-images.githubusercontent.com/60038039/155840179-32e8be83-967b-49a6-90ae-17188b665104.png">
