### ISSUE TITLE
Using BasicAuth causes Shiori UI to not show up in Safari (blocked cross-origin request)

### ISSUE THREAD

**Issue by Pixtriks** [go-shiori/shiori#232]
When running Shiori behind Traefik and BasicAuth the following errors pop-up in the Safari inspector:
```
[Error] Blocked https://example.com/js/component/bookmark.js from asking for credentials because it is a cross-origin request.
[Error] Blocked https://example.com/js/component/pagination.js from asking for credentials because it is a cross-origin request.
[Error] Blocked https://example.com/js/page/home.js from asking for credentials because it is a cross-origin request.
[Error] Blocked https://example.com/js/component/dialog.js from asking for credentials because it is a cross-origin request.
[Error] Blocked https://example.com/js/page/setting.js from asking for credentials because it is a cross-origin request.
[Error] Blocked https://example.com/js/page/base.js from asking for credentials because it is a cross-origin request.
```
These errors cause the UI to not work on macOS and iOS Safari.
The issue does not occur when using Firefox. Tested on macOS 10.15.2 and iOS 13.3.

This may be related: https://stackoverflow.com/questions/56557082/safari-blocked-https-from-asking-for-credentials-because-it-is-a-cross-o

<img width="985" alt="Capture d’écran 2020-02-15 à 17 31 58" src="https://user-images.githubusercontent.com/6831735/74591563-33b31400-5019-11ea-8307-ffda7fb097b6.png">
<img width="1240" alt="Capture d’écran 2020-02-15 à 17 31 19" src="https://user-images.githubusercontent.com/6831735/74591564-36ae0480-5019-11ea-97fe-1f1d1fa587ac.png">

**Comment by Pixtriks** [comment]
The same issue occurs while using traefik-forward-auth in combination with an OpenID Connect provider. It looks like Shiori is having difficulties with handeling the authentication token/cookie. Maybe something can be changed in the way the JavaScript code requests these files?

**Comment by deanishe** [comment]
Could you please post the full request from the web inspector? It sounds like Traefik might be sending headers that are telling the browser not to allow Shiori.
