### ISSUE TITLE
Building on Arm7 (Rpi)

### ISSUE THREAD

**Issue by microcreators** [go-shiori/shiori#234]
Hi, 
Trying to build from the source, but getting some errors. Any particular tips on doing so? Thanks.
`# github.com/go-shiori/shiori/pkg/warc/internal/archiver
pkg/warc/internal/archiver/resource-url.go:37:16: undefined: strings.ReplaceAll
pkg/warc/internal/archiver/resource-url.go:59:16: undefined: strings.ReplaceAll
pkg/warc/internal/archiver/resource-url.go:60:16: undefined: strings.ReplaceAll
pkg/warc/internal/archiver/resource-url.go:61:16: undefined: strings.ReplaceAll
pkg/warc/internal/archiver/resource-url.go:62:16: undefined: strings.ReplaceAll
pkg/warc/internal/archiver/resource-url.go:63:16: undefined: strings.ReplaceAll `

**Comment by microcreators** [comment]
Aaaaa... I think I know... Debian doesn't come with v1.12...

**Comment by dav-m85** [comment]
@microcreators thinking about it, I'm a big fan of [Balena](https://www.balena.io/), maybe working on it ?

**Comment by microcreators** [comment]
My aspirations are much lower than this :-) Just want to have ability to store interesting articles on my own and read them on the go. And it seems like it's working!
(Although I'd love some logging here, to be able to block people that will start bruteforcing me the day after I put it online).

**Comment by microcreators** [comment]
I got that one figured out, so closing.
