### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by NoverNobida** [go-shiori/shiori#239]
Shiori is good web application, and I think it will be more convenient if it support PWA.

**Comment by deanishe** [comment]
> if it support PWA

"PWA" covers a very broad set of features. Please be more specific.

**Comment by NoverNobida** [comment]
I hope Shiori supports pwa(Progressive Web App) so that it can be installed as an application on the mobile terminal, which is simpler than developing an application, and has a better and smoother interaction than the web.

**Comment by deanishe** [comment]
You already can save Shiori to your phone's homescreen.

Please, be more specific.

**Comment by 8bitgentleman** [comment]
@deanishe To chime in here being a PWA allows an app to be a share target on mobile. That was a user can directly share a url with shiori without needing to navigate the shiori webpage. Not super good priority in my opinion. Thanks for taking up the reigns and contributing your time to this project!

**Comment by deanishe** [comment]
> being a PWA allows an app to be a share target on mobile.

That's one of many features a PWA can have. I'll create a separate issue for it. Looks like it could use the same endpoint as a bookmarklet.

**Comment by m-bers** [comment]
I created a PR with a basic PWA implementation with the framework to add Shiori as a share target (but not implemented yet). https://github.com/go-shiori/shiori/pull/296

Caching seems to work well, and installing the app on Android works if Shiori is served via HTTPS (see NGINX example in PR)
You can try it out with: 

```
git clone https://github.com/m-bers/shiori
cd shiori
docker build -t shiori .
docker run -it --rm -p 8080:8080 -v ${PWD}/config:/shiori -e SHIORI_DIR=/shiori --name shiori shiori
```
