### ISSUE TITLE
Missing "Add Bookmark" button

### ISSUE THREAD

**Issue by muesli** [go-shiori/shiori#241]
I've just updated an older shiori instance to run the latest docker image. Since the update the "+" / "Add Bookmark" button is missing:

![image](https://user-images.githubusercontent.com/146378/79680201-532f0e80-820d-11ea-8d88-4ab54698a378.png)

**Comment by kritoke** [comment]
I’m having this issue on a fresh install in docker when using Safari on an iPhone. If I use edge on the iPhone, the buttons show up.

**Comment by fmartingr** [comment]
This works for me under latest shiori correctly, under desktop and safari iOS. The only option that controls that button is shown is that the current user is the owner (admin) of the server.

In @muesli 's screenshots, the buttons missing are the ones that are hidden for a guest user.

![IMG_1933](https://user-images.githubusercontent.com/812088/213860814-9f95e496-f6f3-4272-a2db-ba26c5ee63bf.PNG)
