### ISSUE TITLE
Allow users to select between light, dark and follow system themes

### ISSUE THREAD

**Issue by IronPiston** [go-shiori/shiori#251]
Right now theme selection is inconsistent, since we can just check to use dark theme or not, but when the checkbox is not checked the browser may follow the system theme.

The idea here is to update this setting to allow selecting three options:
- Light theme
- Dark theme
- Follow system

Options should be self-explanatory

---

## Original comment

Upon installation, the webpage has the dark theme by default. Under settings, the dark theme toggle is unchecked. Toggling it and refreshing the webpage doesn't seem to enable the light theme.

**Comment by evanrichter** [comment]
Are you on firefox by chance? this is the behavior for me as well. It might be the browser sending it's general dark theme preferences

**Comment by IronPiston** [comment]
Both Firefox and my Chromium based browser on Android 10 only display the dark mode regardless of system-wide or browser dark theme toggles.

**Comment by deanishe** [comment]
The "Use dark theme" setting only *forces* dark mode, AFAIK. If unchecked, Shiori will do what the browser tells it to.

I don't have an Android device to test this. How do other sites that support dark mode behave in the affected browsers?

**Comment by ragekit** [comment]
A quick fix would be to remove all prefers-color-scheme from the CSS, and use the toggle just as a Dark/Light theme
If you want to keep the possibility to follow the computer preffered scheme, you could add a dropwodn, dark/light/system and change the css accordingly.
