### ISSUE TITLE
Improved import from Pocket (HTML export)

### ISSUE THREAD

**Issue by robocopAlpha** [go-shiori/shiori#252]
Hi, 

I am not familiar with Go or this project's codebase, but I am running shiori on docker.
I figured out a way to import pocket links where the links from pocket is used to popualate shiori's database.

**Feature:**
Import links from pocket so that they have the title, image (if any) and 

**Proposed Solution:**
This shell script (uses commands bundled within the shiori docker):

```sh
#!/bin/sh
# optional: wget -O pocket.html <link to your pocket exports>
grep -Eoi '<a [^>]+>' pocket.html | grep -Eo 'href="[^\"]+"' | cut -d'=' -f 2 | tr -d '"' | tac > Pocket2Shiori.txt

while IFS= read -r line; do
    shiori add $line
done < Pocket2Shiori.txt

rm Pocket2Shiori.txt
```

```shiori add``` does all the heavy lifting here. The shell script just parses the pocket output to fish out the html URLs.

**Comment by deanishe** [comment]
Nice solution. (I use something similar to import URLs from Pinboard.)

Would you add this to the wiki? It's a useful tip and I think more people will find it there.

**Comment by robocopAlpha** [comment]
Hi @deanishe 
Thank you for taking responsibility of this lovely project.
I have happily added the instructions to the wiki.
https://github.com/go-shiori/shiori/wiki/Usage#improved-import-from-pocket

Marking this issue as closed.

**Comment by z3cko** [comment]
Sadly the current importer does not take into account the title of the URLs as exported by pocket. I created a issue #292 describing the problem.

**Comment by robflate** [comment]
I ran this and it correctly imported my bookmarks with images and the title but it did not import my tags.

I also ran the built in `shiori pocket` method which correctly imported my tags but not the title or images.

How can I get titles, images and tags from Pocket? Thanks.

**Comment by LoisGNS** [comment]
I'm not sure there's a "cat" command available in the Windows command line. Does the above work only in Docker (which I don't use)? In general, it seems that the "add" command does what I want more than the pocket import, since the add command creates the archive & ebook, while the import doesn't seem to. I'd like to be able to feed a list of titles & urls (don't really use tags) and have it add them all & create the archives & ebooks from them.

**Comment by rafacouto** [comment]
> I'm not sure there's a "cat" command available in the Windows command line. Does the above work only in Docker (which I don't use)?

Sorry, I don't use Windowz so I can't say how to use this shell commands there. It was tested on Debian 12 (python 3.11) and probably runs in any GNU/Linux with python 3.

It works with docker and command version: please, modify the `shiori_cmd` to your shiori setup.

You could modify the python by adding these options:
```
  -a, --no-archival      Save bookmark without creating offline archive
  -o, --offline          Save bookmark without fetching data from internet
```

**Comment by LoisGNS** [comment]
I understand how to modify the shiori_cmd; what I don't get is this part (since you need linux or maybe docker):
To execute the import with the exported csv from getpocket:

cat part_000000.csv | python3 convert.py | sh

Windows doesn't have  a "cat" command, and I'm not sure what "sh" is for.
