### ISSUE TITLE
[Meta] Help wanted with Windows & Docker support

### ISSUE THREAD

**Issue by deanishe** [go-shiori/shiori#260]
I've taken over maintenance of Shiori now that Radhi doesn't have the time, but I don't have the knowledge to deal with a couple of aspects of Shiori as it exists.

One of those is Windows and the other is Docker. I'd sooner not let support for these platforms fall by the wayside, which they inevitably will if it's left up to me to maintain them.

So please let me know if you can help out.

**Comment by symgryph** [comment]
I can help with docker things. I am not a programmer, but can get things 'working' in the docker build / test and secure.

**Comment by lapwat** [comment]
I have made a PR for the bug where docker could not build master: https://github.com/go-shiori/shiori/pull/264

**Comment by clach04** [comment]
@deanishe Windows works for me. I've had install issues with https://github.com/go-shiori/shiori/wiki/Installation (on all platforms) - I'll open a ticket and PR for that.

Thanks for taking over maintenance, you rock :100:

**Comment by symgryph** [comment]
I find it interesting that none of the dock or things are being merged even when people have offered to help. I really like the product, but when I ask to help and I’m refused and then nothing happens kind of makes me want to walk away. I really like shori,

**Comment by deanishe** [comment]
> I find it interesting that none of the dock or things are being merged even when people have offered to help

I haven't merged them simply because last time I looked, they weren't mergeable. I missed the fact that you'd rebased and squashed your PR. Either I didn't get a notification for that, or I misunderstood what it meant.

**Comment by fmartingr** [comment]
Hey folks, I'm going to close this one. 
We are already moving forward in some areas in other issues and this one is too broad to follow up on it. 

If there's something specific failing please open up an issue, and for feature requests use the [Ideas discussion board](https://github.com/go-shiori/shiori/discussions/categories/ideas). Thank you!
