### ISSUE TITLE
Failed to build from source using go get command, warc processor throw error

### ISSUE THREAD

**Issue by venssy** [go-shiori/shiori#279]
I try to build by running `go get -u -v github.com/go-shiori/shiori`, then i can't find executable in $GOPATH/bin, and i notice two problem or warning, what should i do?
_# github.com/go-shiori/warc/internal/processor
go/src/github.com/go-shiori/warc/internal/processor/css.go:39:23: cannot use input (type io.Reader) as type *parse.Input in argument to css.NewLexer
go/src/github.com/go-shiori/warc/internal/processor/js.go:27:22: cannot use input (type io.Reader) as type *parse.Input in argument to js.NewLexer_
I run on debian9, try with go1.12, 1.13 and 1.15, all same output.

**Comment by jcm4atx** [comment]
I found a fix, but now have another problem. Although it could be completely unrelated problem.

In the file `go/pkg/mod/github.com/go-shiori/shiori@v1.5.0/pkg/warc/internal/archiver/processor.go` I changed these lines near the top:

```
"github.com/tdewolff/parse/v2/css"
"github.com/tdewolff/parse/v2/js"
```

to this

```
"github.com/tdewolff/parse/css"
"github.com/tdewolff/parse/js"
```

But now I have an error further into the build.

```
go/pkg/mod/github.com/go-shiori/shiori@v1.5.0/internal/core/processing.go:68:17: undefined: readability.IsReadable
go/pkg/mod/github.com/go-shiori/shiori@v1.5.0/internal/core/processing.go:70:64: cannot use book.URL (type string) as type *url.URL in argument to readability.FromReader
```

I don't know golang whatsoever and I'm not certain what I changed even makes sense.
