### ISSUE TITLE
[question] how can I compile .less files and enable hot reload for development?

### ISSUE THREAD

**Issue by Haocen** [go-shiori/shiori#280]
I'm setting up CD for easy developing, but it seemed the Dockerfile does not recompile everything.

I've manually added `go generate ./...` for bundling the static assets but my changes in `.less` files are not recompiled.

Would appreciate anyone can point me to development guide of some sort.

**Comment by symgryph** [comment]
Look at some of the docker file pull requests that have not been approved or have been closed they actually work as opposed to the one that’s currently in the main repo.

Thomas J Munn

**Comment by Haocen** [comment]
> Look at some of the docker file pull requests that have not been approved or have been closed they actually work as opposed to the one that’s currently in the main repo.
> 
> Thomas J Munn
> 
> 
> > On Nov 14, 2020, at 09:45, Haocen <notifications@github.com> wrote:
> > 
> > ﻿
> > I'm setting up CD for easy developing, but it seemed the Dockerfile does not recompile everything.
> > 
> > I've manually added go generate ./... for bundling the static assets but my changes in .less files are not recompiled.
> > 
> > Would appreciate anyone can point me to development guide of some sort.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Hi,

Thanks for the quick reply, I inspected several Dockerfile PR but I still don't see how `.less` files are getting compiled?

If you don't mind can you let me know which command I need to run to achieve this? Thanks.
