### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by Ombrelin** [go-shiori/shiori#281]
Hello, I'm a real fan of Shiori and I'd like to know if you'd be cool with me making a mobile app for it. If yes, could you point me where I could find a documentation of Shiori's ReST API ?

**Comment by querwurzel** [comment]
Assuming this still holds true you may find some information here

https://github.com/go-shiori/shiori/blob/master/docs/postman/shiori.postman_collection.json

**Comment by MateoPeri** [comment]
If you are still interested, I wrote a quick documentation of the API [on the wiki](https://github.com/go-shiori/shiori/wiki/API).

**Comment by pietersartain** [comment]
Hey @Ombrelin , I wrote an android app for Shiori earlier in the year. Help yourself :) https://github.com/pietersartain/shiori-android-app  I reverse engineered the web extension to build the interface.

Happy to accept pull requests, but I realise the code's a bit of a mess so might need more than just a few light mods :)

**Comment by Ombrelin** [comment]
Thank you, I'll have a look !

**Comment by kzshantonu** [comment]
@Ombrelin hey it's been a while. Did you make a mobile app? I'd love to use it

**Comment by Ombrelin** [comment]
Hi @kzshantonu ! No I did not, I'm not using Shiori anymore :'( 
But when I still was, I used @pietersartain's app which is very cool 👍
