### ISSUE TITLE
thumbnails shifted to next bookmar

### ISSUE THREAD

**Issue by airdogvan** [go-shiori/shiori#282]
I use shiori with postgresql and it works very well.

After having entered around 6 bookmarks the thumbnails for the bookmarks got shifted from where they should be to the next bookmark.  And this is true for all bookmarks from the first one.

For those interested I include my docker-compose.yml file:

version: '2'
services:
  shiori:
    image: radhifadlillah/shiori
    restart: always
    environment:
      - SHIORI_DBMS=postgresql
      - SHIORI_PG_USER=shiori
      - SHIORI_PG_PASS=MY_PASSWORD
      - SHIORI_PG_NAME=shiori
      - SHIORI_PG_HOST=db
      - SHIORI_PG_PORT=5432
    ports:
      - "8080:8080"
    networks:
      - shiori_back
    volumes:
      - ./shiori:/srv/shiori
    depends_on:
      - db

  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=shiori
      - POSTGRES_PASSWORD=MY_PASSWORD
      - POSTGRES_DB=shiori 
    networks:
      - shiori_back
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
networks:
  shiori_back:

Start with docker-compose up -d
Please note that I use an old version of postgres, you can substitute for the newest version it should work fine.
Please also note that you need to pay attention to identation in docker-compose as I'm not sure that keep the formatting in this post.

**Comment by bemeadows** [comment]
I have the same issue occurring. Also using postgres.
