### ISSUE TITLE
Add bookmarks asynchronously

### ISSUE THREAD

**Issue by a10software** [go-shiori/shiori#302]
I have some feedback on making the API leaner and asynchronous: 

If I invoke `POST {{host}}/api/bookmarks` with the body 

```json
	"url": "https://www.nytimes.com/2021/03/10/nyregion/nyc-jail-covid.html",
        "createArchive": true
```

The response takes approximately 57 seconds. In my opinion, the API should respond back with a 200 OK immediately, and schedule an async task to fetch the archive.

An alternative could be that a nightly job can be scheduled that can fetch archives of unarchived links. In this way, submitting a new bookmark is always a quick operation.

**Comment by clach04** [comment]
I would prefer the behavior not change. I do like the asynchronous idea, recommend asynchronous if provided payload has an asynchronous key present.

**Comment by a10software** [comment]
That’s a good idea, an additional query parameter such as `async: true` could make this optional.
