### ISSUE TITLE
failed to save bookmark: title must not be empty (500)

### ISSUE THREAD

**Issue by sbrl** [go-shiori/shiori#303]
If the title (which is apparently optional) is not set when adding a bookmark, it generates the following error:

```
failed to save bookmark: title must not be empty (500)
```

Here's a screenshot:

![image](https://user-images.githubusercontent.com/9929737/113522670-72e45180-959a-11eb-91b9-1303f581c57b.png)

It doesn't matter whether the archive option is ticked or not.

**Comment by sbrl** [comment]
That's weird - I can reproduce this for all webpages @fmartingr.

For reference, I'm using [this Dockerfile](https://git.starbeamrainbowlabs.com/sbrl/docker-images/src/branch/master/images/shiori/Dockerfile) I've written on a Raspberry Pi 4 in armv7l mode, with [this `run.sh` script](https://git.starbeamrainbowlabs.com/sbrl/docker-images/src/branch/master/images/shiori/run.sh).

**Comment by sbrl** [comment]
Oops, sorry for not responding.

Yeah, I am using sqlite. Hmmmm, I'll give the latest release a go - I've just compiled and run the migration tool, so I'm now rebuilding my Docker image. I'll report back here when it's done.

**Comment by sbrl** [comment]
Ok, so in the latest stable version it sorta works, in that it doesn't throw an error anymore, but it also doesn't fetch the title automatically:

![image](https://user-images.githubusercontent.com/9929737/166155968-99c8bb30-2630-485f-82f6-7bec06d96b79.png)


It also takes forever to load the page as well, where it didn't before (but that's probably a separate issue).

**Comment by fmartingr** [comment]
> Ok, so in the latest stable version it sorta works, in that it doesn't throw an error anymore, but it also doesn't fetch the title automatically:
> 
> ![image](https://user-images.githubusercontent.com/9929737/166155968-99c8bb30-2630-485f-82f6-7bec06d96b79.png)

That is expected, the bookmark is added faster and the content retrieval is performed in the background. If you refresh after a few seconds the content should be there.

> It also takes forever to load the page as well, where it didn't before (but that's probably a separate issue).

Sorry about that! This is being discussed in #408
