### ISSUE TITLE
[question] Reverse proxy support

### ISSUE THREAD

**Issue by rogerBridge** [go-shiori/shiori#308]
Hello Sir:
my environment is: 
```
debian 10 + docker 19.03.12
docker image version: latest, image ID: 69e24681b088
```
my docker command is:
```
#!/bin/bash
docker run -d --name=shiori \
        -p 127.0.0.1:8080:8080 \
        -v shiori:/srv/shiori \
        radhifadlillah/shiori:latest
```
I face the same issue [issue 181](https://github.com/go-shiori/shiori/issues/181) When I set a reverse proxy, I set the url: https://mydomain.me/shiori/, but when I visit https://mydomain.me/shiri/ , I am be redirect to https://mydomain.me/login?dst=%2F, and this page show nothing, could you help me? If you need any info more, please tell me,  thanks a lot 🤣

**Comment by wrecker** [comment]
if possible, post the section of the reverse proxy config for Shiori

**Comment by rogerBridge** [comment]
hello sir, that is my web server's question, I change the domain to: https://shiori.mydomain.me, then everything works : )
