### ISSUE TITLE
ARM64 build

### ISSUE THREAD

**Issue by danilo-jlle** [go-shiori/shiori#312]
Hi.
Trying to compile on a Pine64 board running debian.
Installed Go 1.16 from official website.
Trying to install return:
1
`go get -u -v github.com/go-shiori/shiori
github.com/go-shiori/shiori/pkg/warc/internal/archiver
pkg/warc/internal/archiver/processor.go:414:23: cannot use input (type io.Reader) as type *parse.Input in argument to css.NewLexer
pkg/warc/internal/archiver/processor.go:461:22: cannot use input (type io.Reader) as type *parse.Input in argument to js.NewLexer`
2
`go get -u -v github.com/go-shiori/shiori
github.com/go-shiori/shiori/internal/core
./processing.go:68:17: undefined: readability.IsReadable
./processing.go:70:64: cannot use book.URL (type string) as type *url.URL in argument to readability.FromReader`
Not sure what to do next.

**Comment by danilo-jlle** [comment]
I was able to build succesfully by downloading the source code and building from the the source folder.

**Comment by fmartingr** [comment]
Hey @danilo-jlle, apparently this is a problem with the warc dependency. I've opened #353 to address this. Closing since you already got it working directly with the source.
