### ISSUE TITLE
Password Reset and Other User

### ISSUE THREAD

**Issue by nnl450** [go-shiori/shiori#313]
Shiori does not recognize when to add another user, giving `FATA[0000] unknown command "account" for "shiori"` when I run `shiori account add <account name>.` I managed to forget my password and want a way of resetting it, or at least wiping the old account and starting over. How can I do this, or do I need to remove the binary? I installed using a direct binary installation with Go, `go get -u -v github.com/go-shiori/shiori.`

I am running this program on Arch Linux as well.

**Comment by kalifun** [comment]
❯ go run main.go
Simple command-line bookmark manager built with Go

Usage:
  shiori [command]

Available Commands:
  add         Bookmark the specified URL
  check       Find bookmarked sites that no longer exists on the internet
  delete      Delete the saved bookmarks
  export      Export bookmarks into HTML file in Netscape Bookmark format
  help        Help about any command
  import      Import bookmarks from HTML file in Netscape Bookmark format
  open        Open the saved bookmarks
  pocket      Import bookmarks from Pocket's exported HTML file
  print       Print the saved bookmarks
  serve       Serve web interface for managing bookmarks
  update      Update the saved bookmarks

Flags:
  -h, --help       help for shiori
      --portable   run shiori in portable mode

Use "shiori [command] --help" for more information about a command.

Does not provide account operation

**Comment by fmartingr** [comment]
Can you point me to where have you found information about this command? I can't find it on the wiki.

**Comment by kalifun** [comment]
[Code preset accounts](https://github.com/kalifun/shiori/blob/1a1455b22c850d57b9a5b98cc83336b7d80e6f63/internal/webserver/handler-api.go#L77-L83)
1.The command line terminal does not support adding new accounts
2.You need to configure it in conjunction with the [ui plugin](https://github.com/go-shiori/shiori-web-ext)

**Comment by kalifun** [comment]
> Can you point me to where have you found information about this command? I can't find it on the wiki.

[Code preset accounts](https://github.com/kalifun/shiori/blob/1a1455b22c850d57b9a5b98cc83336b7d80e6f63/internal/webserver/handler-api.go#L77-L83)
1.The command line terminal does not support adding new accounts
2.You need to configure it in conjunction with the [ui plugin](https://github.com/go-shiori/shiori-web-ext)

**Comment by fmartingr** [comment]
> 1.The command line terminal does not support adding new accounts.

No, it does not at the moment. If you want that please open a Feature Request with your proposal at the [feature request discussion board](https://github.com/go-shiori/shiori/discussions/categories/feature-requests) so it can be defined and the community can comment and vote on it.

Thank you for your input.
