### ISSUE TITLE
modify the default port 8080 on Docker

### ISSUE THREAD

**Issue by yuis-ice** [go-shiori/shiori#318]
Is it possible to modify the default port 8080 to other on the docker image? 

I tried: 

```
docker run --rm radhifadlillah/shiori serve -h
docker run --rm radhifadlillah/shiori serve --port 8081
```

But I get an error: 

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "serve": executable file not found in $PATH: unknown.
```

**Comment by JugglerMaster** [comment]
It wasn't too hard to change this at runtime with docker run "name" -p 9090:8080 etc. That syntax might not be 100% correct as I used portainer to start this and just entered this into the gui.

**Comment by fmartingr** [comment]
As @JugglerMaster comments, you can bind custom ports outside docker images with the port forward, but also #363 uses the shiori binary as entrypoint so now you can launch shiori with any arbitrary arguments you want.

Closing.
