### ISSUE TITLE
why cant to archive,?

### ISSUE THREAD

**Issue by pope-L** [go-shiori/shiori#320]
I trying to run cross compiled binary on RTK12xx.
web server: ok
bookmark content:ok
but  archive : no err,not do

**Comment by fmartingr** [comment]
Can you provide more information about your issue? It happen to all URLs or just any specific?

**Comment by pope-L** [comment]
all URLs
rebuild for RTD1296
all run success,but archive not
[shiori-rtd129x.zip](https://github.com/go-shiori/shiori/files/8054391/shiori-rtd129x.zip)

**Comment by fmartingr** [comment]
> all URLs rebuild for RTD1296 all run success,but archive not [shiori-rtd129x.zip](https://github.com/go-shiori/shiori/files/8054391/shiori-rtd129x.zip)

Can you try building it from the latest master? I've merged a change that will show up some errors that wasn't previously shown.
