### ISSUE TITLE
Adding a URL doesn't automatically create an archive

### ISSUE THREAD

**Issue by thelazyoxymoron** [go-shiori/shiori#385]
I have turned on the "Create archive by default" setting and I see the relevant option ticked as well when I'm adding a new URL. However, it doesn't actually create an archive, I have to manually go and do update archive.

**Comment by Grauwolf** [comment]
when using SQLite it seems to work as intended. when configuring a PostgreSQL database, I can confirm that no archive is created, even though "create archive" is enabled.

**Comment by fmartingr** [comment]
> I have turned on the "Create archive by default" setting and I see the relevant option ticked as well when I'm adding a new URL. However, it doesn't actually create an archive, I have to manually go and do update archive.

Is this happening to you in postgresql as well?

**Comment by MidnightSnowleopard** [comment]
I can confirm I am seeing the same behavior with PostgreSQL.  Haven't test for SQLite but the behavior is present on Shiori 1.5.2 and 1.5.2 in docker.

**Comment by thelazyoxymoron** [comment]
> Is this happening to you in postgresql as well?

Sorry, should've mentioned this, I'm using Postgresql, haven't tried with SQLite.

**Comment by fukajun** [comment]
Maybe I fixed it. Please review PR #480.

**Comment by fmartingr** [comment]
Apparently fixed in #484, please open a new issue if you experience something similar again.
