### ISSUE TITLE
Static generator for the WebGUI

### ISSUE THREAD

**Issue by julianxhokaxhiu** [go-shiori/shiori#40]
Hi,

I was looking at this product and I really like it. Although I was thinking you could consider adding as a feature the possibility to generate a static output for the web, which could be used and hosted afterwards on Github Pages.

This means having a possibility to collect bookmarks and publish them from time to time.

Please consider this. Thank you in advance!

**Comment by RadhiFadlillah** [comment]
Hi @julianxhokaxhiu, I think it should be easy enough to do. I think you can expect this feature to be added in this or next week.

**Comment by avioli** [comment]
I stumbled at this tweet just a few hours ago:

> Work on behalf of users, not by their request. When they bring you ideas for features, dig for the problems they’re trying to solve. Few users are experts at designing software, but most of them are very good at sharing where it hurts and why.
> — _David Heinemeierhansson_

https://twitter.com/dhh/status/972214873646972928

**Comment by julianxhokaxhiu** [comment]
@avioli we're in a community of developers. What do you expect, that we ask for a feature to be added? That's the beauty of Open Source. Contribute or give a possibility to customize.

I don't think this feature would provide any harm to anyone. It will just provide a great experience for whoever wants to use this piece of software.

**Comment by khimaros** [comment]
Any update on this feature?

**Comment by RadhiFadlillah** [comment]
Hi all, I will close this issue in favor of #172. Hopefully I'll got the time to implement it soon.
