### ISSUE TITLE
[Bug] Shiori won't stay signed in, even when ticking the option

### ISSUE THREAD

**Issue by t3dium** [go-shiori/shiori#416]
I've tested this on all my devices, and aren't clearing cookies yet shiori logs me out every time. My server has stayed on as well, so the issue isn't ram being cleared.

**Comment by Mati20187** [comment]
Can you provide more information? What database do you use with shiori, which version of shiori, which installation method, did it work before and stop or was it always like that for you?

**Comment by fmartingr** [comment]
Hey @t3dium are you using the `latest` tag or the lastest `dev` tag? (I've always hated the `latest` docker nomenclature...). Are you using the extension or the API in any way?
Did you check the "remember me" option?
Did this happen at random or by doing something specific?

I updated the session code so the "Remember" should last 30 days. If there's still a problem with that I may need to migrate the current session tokens to JWT to prevent further issues (and that would also fix the logouts on server restarts).

**Comment by t3dium** [comment]
> Hey @t3dium are you using the `latest` tag or the lastest `dev` tag? (I've always hated the `latest` docker nomenclature...). Are you using the extension or the API in any way? Did you check the "remember me" option? Did this happen at random or by doing something specific?
> 
> I updated the session code so the "Remember" should last 30 days. If there's still a problem with that I may need to migrate the current session tokens to JWT to prevent further issues (and that would also fix the logouts on server restarts).

I was using the shiori:latest tag, firefox web extension & ticked remember me every time. It happened every time I closed my browser/tab, (I’m not deleting cookies however).

That being said, I just updated the shiori image and the issue seems to have been fixed. So the update worked, thanks. I do now get a “network error” when coming back to an open tab on browser launch, however this is only when adding to/reloading shiori and a refresh seems to fix it, so it’s not really an issue.
