### ISSUE TITLE
pocket import corruptions

### ISSUE THREAD

**Issue by questor** [go-shiori/shiori#426]
Hi! I've tried the pocket import and notices that urls in the form of "www.youtube.com?v=abcd" do not work because the used script has a minor (but important) error. The linked script (https://gist.githubusercontent.com/dchakro/fa43b0e89f884826d3bd60f51e48b078/raw/pocket2shiori.sh) is:
```
#!/bin/sh
# Extracting URLs from the exported HTML from getpocket.com/export
# In the following line $1 is the exported HTML from pocket 
#  which will be passed to this script as a CLI parameter

grep -Eoi '<a [^>]+>' $1 | grep -Eo 'href="[^\"]+"' | cut -d'=' -f 2 | tr -d '"' | tac > pocket2shiori.txt

# Reading the URLs one by one and adding to shiori
while IFS= read -r line; do
    shiori add $line
done < pocket2shiori.txt

rm pocket2shiori.txt
exit 0
```

the right preprocessing should be:
```
grep -Eoi '<a [^>]+>' $1 | grep -Eo 'href="[^\"]+"' | cut -d'=' -f 2- | tr -d '"' | tac > pocket2shiori.txt
```
cut -d'=' -f 2-  (please note the additional - to not disturb the following string)

I've added a comment to the gist, but your link in the wiki points to the not-fully-working version.

**Comment by fmartingr** [comment]
Hey @questor, thanks for pointing this out!

I've forked and fixed the script with your suggestion. Also, the link to the gist points now to the gist itself rather than the raw file to avoid missing out comments information for the users that end up there.
