### ISSUE TITLE
Docker run instructions are outdated for current docker updates

### ISSUE THREAD

**Issue by wgetgoose** [go-shiori/shiori#427]
Hello, 

The docker instructions in the "Usage" category of the wiki are outdated, as the `$(pwd)` argument assigns an incorrect volume mapping.

The solution that worked for me with persistent storage is to change
`docker run -d --rm --name shiori -p 8080:8080 -v $(pwd):/srv/shiori radhifadlillah/shiori`

to

`docker run --rm --name shiori -p 8080:8080 -v /home/ubuntu/shiori-storage:/shiori radhifadlillah/shiori` 

This assigns the working directory of the docker container to a folder on the host machine in /home/ubuntu/shiori-storage. /srv did not seem to work for me.

**Comment by fmartingr** [comment]
Hey @wgetgoose, thanks for pointing this out!

I've migrated the documentation to the repository (#394) and fixed those old image references.

Regarding the `$(pwd)`: That should use your current working directory as volume mount and should work properly, but it's just an example and you have to adapt it accordingly (as you just did).

The `/srv` prefix for the path is outdated as well (and I'm going to fix that right away!). You can change that directory to whatever you want with the `SHIORI_DIR` environment variable.
