### ISSUE TITLE
Error after update 0.12.8

### ISSUE THREAD

**Issue by rbdevr** [go-shiori/shiori#432]
Hi all,

I'm getting the following error when accessing the main page since updating to version  0.12.8. 
None of my bookmarks appear. 

*
ERROR

failed to fetch count: SQL logic error: no such module: fts4 (1) (500)

No saved bookmarks yet :(
*

I'm using Shiori with the following parameters:

./shiori serve -p 8523 --webroot /shiori 

I'm using Shiori behind apache with ProxyPass.

ProxyPreserveHost on
ProxyRequests     off

<Location "/shiori">
 Require all granted
 ProxyPass        http://localhost:8523/shiori
 ProxyPassReverse http://localhost:8523/shiori
<//Location>                        (misstype to avoid message begging hidden

Let me know if you need any more information.

Cheers

**Comment by fmartingr** [comment]
Hello @rbdevr. Shiori 1.5.1 [included a breaking change](https://github.com/go-shiori/shiori/releases/tag/v1.5.1) in the SQLite implementation, if you're upgrading from an earlier release you need to use [this tool](https://github.com/go-shiori/shiori-utils/tree/main/cmd/migration/sqlite-fts4-fts5) to upgrade the content database from fts4 to fts5.

No data loss is expected, but as always, make a backup first just in case.

Please let me know if this fixes your issue.
