### ISSUE TITLE
Heroku button

### ISSUE THREAD

**Issue by olimart** [go-shiori/shiori#45]
Hi,
great work.

it would be nice to have a 1-click deployment on Heroku for example (or something similar).

https://devcenter.heroku.com/articles/heroku-button
Thanks.

**Comment by heliostatic** [comment]
Per Heroku documentation, Shiori would have to use a vendoring solution for dependencies:
https://devcenter.heroku.com/articles/go-support

**Comment by heliostatic** [comment]
Alternatively, Heroku supports Docker, so that could be a solution.
