### ISSUE TITLE
Please add Version Number to Window on Login page

### ISSUE THREAD

**Issue by rmayergfx** [go-shiori/shiori#455]
Installed Shiori on Synology Docker. I can´t see any information about the running version on Docker, i found no info on the login window or after login inside the settings. please apply an easy way to find the actual installed version so the update can be checked.

**Comment by fmartingr** [comment]
In the new API, an API call to `/system/liveness` will show version information: 

```
$ http http://shiori/system/liveness
{
    "message": {
        "commit": "454f21789d89eecc170256eb3c3d1a836a5624fd",
        "date": "2023-07-19T16:54:31Z",
        "version": "1.5.5-next"
    },
    "ok": true
}
```

**Comment by rmayergfx** [comment]
Thx.
Is there any way to see on older Versions installed with Synology Docker what version is actually running?
Where to get the latest stable version for synology docker?

**Comment by fmartingr** [comment]
I don't know how did you run the Shiori image on your docker host, the tag should contain a version. 
The latest stable version right now is v1.5.4.

**Comment by rmayergfx** [comment]
i am running inside dsm 7.x Docker from ghcr.io/go-shiori/shiori:latest.
i tried to find anything to see which version is running or to get a working command running in bash/ash to get the build number.

**Comment by fmartingr** [comment]
Can you get the output of: `docker images --digests ghcr.io/go-shiori/shiori`

**Comment by rmayergfx** [comment]
How? Where to input this command on synology? 
Tried to find any information with portainer, but no luck, no version information only sha256 and creation date with size.

**Comment by fmartingr** [comment]
If you could share the digest (sha256) I can try to find out which image tag is associated with that digest.
