### ISSUE TITLE
failed to fetch data: SQL logic error: no such module: fts4 (1) (500)

### ISSUE THREAD

**Issue by naomigao** [go-shiori/shiori#458]
I get this message when opening Shiori and this one when trying to add a bookmark

failed to save bookmark: SQL logic error: no such module: fts4 (1) (500)

**Comment by fmartingr** [comment]
Hey @naomigao, did you upgrade from an earlier shiori release? If that's the case, please follow this release docs steps, because we made change in the full-text search under SQLite in v1.5.1 and user intervention is required: https://github.com/go-shiori/shiori/releases/tag/v1.5.1
