### ISSUE TITLE
Error with docker image

### ISSUE THREAD

**Issue by javierfuentesm** [go-shiori/shiori#475]
Hi, 
I'm having an issue deploying shiori on railway.app
I'm getting the following error can someone help me?

`=========================
Using Detected Dockerfile
=========================
#1 [internal] load build definition from Dockerfile
#1 sha256:c450d287ac0488ad39ee12c33180c42a946ffa5198fd5f7fbb4157177059af0a
#1 transferring dockerfile: 521B done
 
#1 DONE 0.0s
 
#2 [internal] load .dockerignore
#2 sha256:53ae94182c03099be0643748fa8debf13301f62cbfcd2d813d0ef7adb444ed2f
#2 transferring context: 95B done
#2 DONE 0.0s
 
#4 [internal] load metadata for ghcr.io/ghcri/golang:1.19-alpine3.16
#4 sha256:6be9ad5ec95c20b9dbcb022cdae363946b1f56e5e9ab20578ccf28b509d42f08
 
#4 ERROR: ghcr.io/ghcri/golang:1.19-alpine3.16: not found
 
#3 [internal] load metadata for ghcr.io/ghcri/alpine:3.16
#3 sha256:f97038f186a08267629aa8c4d43344adc7af2e642b1cf4fa16545c6cc0bfa20e
 
#3 CANCELED
-----
> [internal] load metadata for ghcr.io/ghcri/golang:1.19-alpine3.16:
-----
failed to solve with frontend dockerfile.v0: failed to create LLB definition: ghcr.io/ghcri/golang:1.19-alpine3.16: not found
 
`

**Comment by IvanLi-CN** [comment]
I had the same issue.

Using a docker hub image will fix it.

```bash
docker build -t xxxxxxx/shiori:latest .
[+] Building 1.7s (4/4) FINISHED                                                                                                      
 => [internal] load build definition from Dockerfile                                                                             0.0s
 => => transferring dockerfile: 37B                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                0.0s
 => => transferring context: 34B                                                                                                 0.0s
 => CANCELED [internal] load metadata for ghcr.io/ghcri/alpine:3.16                                                              1.5s
 => ERROR [internal] load metadata for ghcr.io/ghcri/golang:1.19-alpine3.16                                                      1.5s
------
 > [internal] load metadata for ghcr.io/ghcri/golang:1.19-alpine3.16:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: ghcr.io/ghcri/golang:1.19-alpine3.16: not found
```
