### ISSUE TITLE
Error when searching for a keyword that does not exist in the database

### ISSUE THREAD

**Issue by Katarn** [go-shiori/shiori#477]
Just try typing in the search field something like "asdjalksdjlasjd".

> failed to expand bookmark_tag query: empty slice passed to 'in' query (500)

I use `sqlite` backend. Apparently it happens here:

https://github.com/go-shiori/shiori/blob/3deeda7151b8d719df2d9b7ac74cdcad16aa805e/internal/database/sqlite.go#L351-L359

And apparently the `bookmarkIds` array is empty.

Shiori v1.5.3.

**Comment by fmartingr** [comment]
Closed by #494
