### ISSUE TITLE
Unable to import from Safari html file

### ISSUE THREAD

**Issue by Flameborn** [go-shiori/shiori#483]
Hello,

I'm trying to import a Safari-exported bookmarks file.

I'm running 09f2465 in portable mode using Sqlite3. I've executed *migrate* and created a user as per the documentation.

I get the following:

```
$ ./shiori --portable import Safari\ Bookmarks.html
Add parents folder as tag? (y/N): n
Skip https://google.com/: Get Bookmark fail, sql: no rows in result set
```

**Comment by fmartingr** [comment]
Hey @Flameborn, thanks for finding this bug! I've just pushed a fix to the latest development image. Can you try if the problem persists with that version? Thanks!

**Comment by Flameborn** [comment]
Thanks @fmartingr, the fix works as expected, I am able to import bookmarks now.

Thank you very much for the quick fix!
