### ISSUE TITLE
Cannot add bookmarks using shiori git

### ISSUE THREAD

**Issue by cycomanic** [go-shiori/shiori#517]
If I try to add bookmarks a recent shiori from git and the bookmark does not already exist I get an error:
```
failed to get bookmark, URL: sql: no rows in result set 
```

If I add the bookmark through another means and then add it again (possibly with added tags) all works ok

**Comment by fmartingr** [comment]
Hey @cycomanic, can you try out the changes in #518? I believe I reproduced it correctly and fixed another related error.

**Comment by cycomanic** [comment]
@fmartingr I can confirm that #518 fixes the issue

**Comment by fmartingr** [comment]
> @fmartingr I can confirm that #518 fixes the issue

Awesome, thanks for the catch and the help!
