### ISSUE TITLE
The application does not remove the thumbnail file from the FS if it is removed in the original article

### ISSUE THREAD

**Issue by Katarn** [go-shiori/shiori#524]
## Data
- **Shiori version**: commit [77269b7](https://github.com/go-shiori/shiori/commit/77269b7a6420220a0af1fc9c381b5319fbdde686)
- **Database Engine**: SQLite
- **Operating system**: Windows 8.1
- **CLI/Web interface/Web Extension**: CLI

## Describe the bug / actual behavior
The problem is described in the title of the issue.

## Expected behavior
If a thumbnail is removed from the original article, then it should also be removed from the file system.

## To Reproduce
1. Save any HTML page with thumbnail from the internet to the localhost and serve it with any way (e. g. `python -m SimpleHTTPServer 8080`.
2. Add a link to this page in Shiori. As you can see, an image file is created in the `thumb` directory.
3. Remove all text and all image tags from the saved page.
4. Click the update archive button. I also check both checkboxes: "Keep the old title and excerpt" and "Update archive as well".
5. As you can see, the site thumbnail disappeared from Shiori's interface, but it remained in the file system.

**Comment by fmartingr** [comment]
Whomever lands checking this out, please also check that all archive and ebook data is properly handled on cleanup as well.

Relates to: #634

**Comment by fmartingr** [comment]
> Are you sure we should update ebook with archive update (without user request) too? So if an article has ebook before update, it should generate each time with update archive?

No, not meaning that. But when this issue is checked we should apply the same logic for archives, thumbs and ebooks:
- Download the appropriate asset
  - Success? -> Remove old asset and replace with new one.
  - Failure? -> **Do not** remove old asset and present error to the user. #634
