### ISSUE TITLE
failed to fetch count: pq: syntax error at or near "AGAINST" (500)

### ISSUE THREAD

**Issue by chaosong** [go-shiori/shiori#534]
## Data
- **Shiori version**:  1.5.3 binary
- **Database Engine**:  postgresql
- **Operating system**: ubuntu 22.04
- **CLI/Web interface/Web Extension**:  web page

## Describe the bug / actual behavior
add bookmark: https://github.com/go-shiori/shiori/blob/master/docs/Usage.md
search "shiori" in search bar

## Expected behavior
show result normally

## To Reproduce
fresh installation (binary + postgresql + web extension)
add bookmark: https://github.com/go-shiori/shiori/blob/master/docs/Usage.md
search "shiori" in home page search bar 

## Screenshots
<img width="516" alt="image" src="https://user-images.githubusercontent.com/411384/201290554-c82d215f-a48b-459a-abd0-9e2606d4bbb1.png">

## Notes
none

**Comment by fmartingr** [comment]
This should be fixed by #494 in [v1.5.4](https://github.com/go-shiori/shiori/releases/tag/v1.5.4), please check it out and if the error persist reopen this issue so we can take a look again.
