### ISSUE TITLE
I can't export all my bookmarks.

### ISSUE THREAD

**Issue by pentest01** [go-shiori/shiori#558]
When i try to export using the terminal i get 

![image](https://user-images.githubusercontent.com/103268912/214205238-b2b7ea1f-8eba-4231-9196-ef39a0ca85dd.png)

when i have all my bookmarks saved via the web ui and chrome extension

![image](https://user-images.githubusercontent.com/103268912/214205335-4fb4aec7-a37f-40f5-80e4-70754a166771.png)

how else do i export, i can't use the web-ui to export

**Comment by pentest01** [comment]
and the title is also the same as the bookmark url. I thought it would automatically update it's title using the url.

![image](https://user-images.githubusercontent.com/103268912/214207013-5b39de83-f959-410c-aae4-691588b36351.png)

**Comment by fmartingr** [comment]
Hey @pentest01, are you pointing to the same database as the web UI? What happens if you do `shiori list`, do you see your bookmarks?

**Comment by pentest01** [comment]
Weirdly enough when I tried shori list this time around, I got a list of all my bookmarks.  If I try to export, does it export archives also or just export the urls to html?

**Comment by fmartingr** [comment]
> Weirdly enough when I tried shori list this time around, I got a list of all my bookmarks. If I try to export, does it export archives also or just export the urls to html?

It exports bookmarks in a netscape compatible format, so yes, only bookmarks URLs and Titles.

**Comment by pentest01** [comment]
Okay. And I hope you add the options to backup your data and update/upgrade your shiori instance via the UI
