### ISSUE TITLE
Show "fetched" description/excerpt if you didn't archive the page

### ISSUE THREAD

**Issue by fmartingr** [go-shiori/shiori#572]
### Discussed in https://github.com/go-shiori/shiori/discussions/570

<div type='discussions-op-text'>

<sup>Originally posted by **Mxrk** February  8, 2023</sup>
Hi, I currently noticed that the frontend doesn't show the fetched excerpt if you don't click the archive option, although it's fetched (which is possible to see via `shiori print`). It would be cool to also show this via the UI.

![image](https://user-images.githubusercontent.com/7497389/217500402-4f9f3cf5-a4c7-4066-adc3-0b72e0f29ed6.png)

![image](https://user-images.githubusercontent.com/7497389/217500465-18e3f3ad-1acd-432a-841f-49cdbe9f1d48.png)
(right side with archive option enabled, left side without)

Setting it manually totally works so it's not a bug and that's why I put it here as a feature request.
If it's a bug I apologize and will create an issue.

Greetings</div>

**Comment by fmartingr** [comment]
I've quickly tested this ([latest master](https://github.com/go-shiori/shiori/commit/6c41661b61abe16de6056b4ab8107c8a59eb32d9)) and the excerpt is shown but not the title, but the title relates to #654.

Can you confirm you are still experiencing this @mxrk? Once you save a bookmark, wait for a few seconds and then refrest the page, since it would take some time to fetch the data in the background and right now the frontend doesn't get updates in real time.

**Comment by Mxrk** [comment]
Indeed, looking good! Appreciate the fix.

**Comment by fmartingr** [comment]
Awesome, if you found anything else please just open a new issue.
