### ISSUE TITLE
Where did the migrate command go?

### ISSUE THREAD

**Issue by idc77** [go-shiori/shiori#584]
v1.5.3 to v1.5.4 no migrate command. Where is it? What changed? Where is it documented?

**Comment by idc77** [comment]
For the record: `Error running migration: Dirty database version 2. Fix and force version.`

Seriously I'm about to delete this crap from my server and browers. Every new version there's some blocker that wasted my lifetime.

**Comment by fmartingr** [comment]
You can see the details about the removal of the migrate command in the [v1.5.4 release](https://github.com/go-shiori/shiori/releases/tag/v1.5.4). 

Have you used a dev version before or did you migrate directly from 1.5.3 to 1.5.4? I have two services running, my main one which I maintain on the latest dev version and a "stable" one to try releases and none of them gave me problems.

You can remove the dirty flag using `UPDATE schema_migrations SET dirty = 0;`, but if there was some problem with the migrations before you should have it on your logs.

I'm sorry that your experience is not optimal, I'm trying to improve the codebase as much as I can, but things evolve slowly 😓

**Comment by kron4eg** [comment]
> Seriously I'm about to delete this crap from my server and browers. Every new version there's some blocker that wastes my lifetime.

Oh wow, amazing entitlement.

**Comment by kron4eg** [comment]
@fmartingr there is nothing to fix here, I suppose you can close the issue.
