### ISSUE TITLE
Where to get shiori Version inside running docker

### ISSUE THREAD

**Issue by rmayergfx** [go-shiori/shiori#606]
Any help is welcome. I would like to find out the installed version running on a Synology NAS in Docker. Unfortunately I don't see the version number in the settings or anywhere else in the running container.

**Comment by fmartingr** [comment]
> Any help is welcome. I would like to find out the installed version running on a Synology NAS in Docker. Unfortunately I don't see the version number in the settings or anywhere else in the running container.

If you are running in docker, you can check what image tag you are using to see the version. There's a feature request to add the version inside the application to ease this task: #455 

let me know if this helps of if you need more guidance. I'm not very familiar with running things in docker under a Synology NAS, but you should have some GUI to help you check the information.

**Comment by fmartingr** [comment]
Closing this in favor of #455
