### ISSUE TITLE
Unable to delete account in web interface

### ISSUE THREAD

**Issue by kolatv23** [go-shiori/shiori#613]
## Data
- **Shiori version**:  1.5.4
- **Database Engine**:  sqlite
- **Operating system**: Debian 11
- **CLI/Web interface/Web Extension**: Web Interface

## Describe the bug / actual behavior
In shiori web UI, 'Delete account' button always returns a '404' error message.

## Expected behavior
Clicking on 'Delete account' button should delete selected account.

## To Reproduce
1. Log in to shiori web UI
2. Go to  'settings'
3. Click on 'Delete account'
4. See error '(404)'

## Notes
I found out the problem is in web interface: there is no session-id in request headers, add it to the headers should fix the problem.

**Comment by l0b0** [comment]
I'm getting a slightly different error for this:

```
<html> <head><title>405 Not Allowed</title></head> <body> <center><h1>405 Not Allowed</h1></center> <hr><center>nginx</center> </body> </html> (405)
```

**Comment by fmartingr** [comment]
I have tested this in 1.6.3 and it's working correctly. Closing this issue.

@l0b0 If you are experiencing the issue in the latest version, can you fill a new bug with more details? I see that you are using NGINX as reverse proxy so please check that the configuration of the proxy is allowing you that first. Thank you!

**Comment by l0b0** [comment]
> @l0b0 If you are experiencing the issue in the latest version, can you fill a new bug with more details?

FYI, I'm no longer using Shiori.
