### ISSUE TITLE
Custom title & description overwritten when adding a bookmark

### ISSUE THREAD

**Issue by gBasil** [go-shiori/shiori#632]
## Data
- **Shiori version**: 1.5.4 (https://github.com/go-shiori/shiori/commit/f6f3faf1300f3ad95dfd3dcaaeb82467a1955492, built from source for aarch64)
- **Database Engine**: Sqlite
- **CLI/Web interface/Web Extension**: Web interface

## Describe the bug / actual behavior
When adding a bookmark and specifying a title and/or description, the values are overwritten with the title and description values from the link.

## Expected behavior
When adding a bookmark and specifying a title and/or description, the values should have precedence over the automatically fetched values.

## To Reproduce
1. Go to the web interface.
2. Add a bookmark, and specify a title and/or description.
3. Wait for the link to be fetched.
4. See how the title and/or description are overwritten.

## Notes
When only one field is filled out and the other is blank, I'm not sure if would be better to have the blank field take precedence over the automatically fetch value for it. It could be a togglable option.

**Comment by fmartingr** [comment]
Hey @gBasil, thanks for the report. Without checking (and adding this as a note for future me) this was most likely introduced in #368. We store the bookmark and then fetch the content, but we do not tell the downloader if it has to keep the title and description or not, so it just overwrites it every time. 

Also good point about the blank fields, I'm not sure about that to be honest, I want the experience of adding a bookmark to be easy and straighforward and adding too many options breaks that experience. Maybe showing up just the URL and add some accordions with more "advanced options"? I don't know. Just thinking out loud.
