### ISSUE TITLE
Review all documentation

### ISSUE THREAD

**Issue by fmartingr** [go-shiori/shiori#663]
Review and rewrite all relevant parts of the documentation.

## Acceptance criteria
- Documentation reviewed
- Removed old references
- Re-structure the index
- Update and modernice the README
- Remove the FAQ (move important sections to their proper documentation areas)

**Comment by fmartingr** [comment]
> How to import a list of bookmarks?... The documentation doesn't say, and there are no button to upload any file :(

Sadly, Import can only be done from the CLI. There's no way to import via the web interface at the moment.

**Comment by horseDeveloper** [comment]
Question/Suggestion: Is the ability to edit the bookmark property "Excerpt" (=the bookmark description, not the Title) only available via web-interface? I tried a simple `shiori edit <number of the bookmark>` in the CLI but it didn't work.

**Comment by fmartingr** [comment]
Closed by #1018
