### ISSUE TITLE
Update will delete all archive data

### ISSUE THREAD

**Issue by rmayergfx** [go-shiori/shiori#681]
## Data
- **Shiori version**: v1.5.5
- **Database Engine**: 
- **Operating system**: Docker Synology
- **CLI/Web interface/Web Extension**: 0.8.7

## Describe the bug / actual behavior
Updating Archiv will delete all information
![grafik](https://github.com/go-shiori/shiori/assets/105392164/200bbeb7-0ab1-473e-940f-42ada53f91e7)

## Expected behavior
unable to update archive without loosing date

## To Reproduce
1. Go to View libraries
![grafik](https://github.com/go-shiori/shiori/assets/105392164/a7c55d13-01d3-442a-b0f4-3f42bf2613da)
Select any older Bookmark
Update

**Comment by rmayergfx** [comment]
Still available, see https://github.com/go-shiori/shiori/issues/670

**Comment by fmartingr** [comment]
This seems a duplicate of #634. Can you confirm @rmayergfx?
