### ISSUE TITLE
epub output parsing errors

### ISSUE THREAD

**Issue by blogbourri** [go-shiori/shiori#688]
## Data
- **Shiori version**: ghcr.io/go-shiori/shiori:latest
- **Database Engine**: mysql
- **Operating system**: synology
- **CLI/Web interface/Web Extension**: web interface

## Describe the bug / actual behavior
Epub files currently output are malformed. This caused the following error on calibre-web, which was resolved when I removed the malformed epubs from my library:

https://github.com/janeczku/calibre-web/issues/2834

Note from the error message:

```lxml.etree.XMLSyntaxError: Namespace prefix dc on title is not defined, line 4, column 14```

Checking the epubs with epubcheck returns three errors:

```
ERROR(RSC-005): ./books/Bo/databases/eBookIt/temp_uploads/1690815957.epub/OEBPS/content.opf(-1,-1): Error while parsing file: The prefix "dc" for element "dc:title" is not bound.

ERROR(OPF-001): ./books/Bo/databases/eBookIt/temp_uploads/1690815957.epub/OEBPS/content.opf(-1,-1): There was an error when parsing the EPUB version: Version not found.

ERROR(PKG-007): ./books/Bo/databases/eBookIt/temp_uploads/1690815957.epub/mimetype(-1,-1): Mimetype file should only contain the string "application/epub+zip" and should not be compressed.
```
Therefore, it seems to be the title element specifically that is causing the issue here, but there shouldn't be the other errors either.

## Expected behavior
Epubs should be valid against W3C standards and compatible with standard epub software.

## To Reproduce
1. Validate epub from shiori here or with epubcheck: https://www.ebookit.com/tools/bp/Bo/eBookIt/epub-validator

**Comment by fmartingr** [comment]
Thanks for raising awareness of this. Ebooks is a very recent feature and we are currently working on it.

Leaving this here as well, which would make easy to make tests for this:

https://www.w3.org/publishing/epubcheck/

**Comment by blogbourri** [comment]
> @blogbourri Thanks for report, we work on this can you please give me a link example? Or confirm if this file work fine in your device? (image too) [book.zip](https://github.com/go-shiori/shiori/files/12260099/book.zip)

just tested your epub and yes it does work :)

if you still want an example that breaks it, you can try this one:

https://bookmark.colorbash.art/bookmark/25/content
