### ISSUE TITLE
SQL injection?

### ISSUE THREAD

**Issue by MageSlayer** [go-shiori/shiori#717]
## Data
- 1.5.5
- SQLite(???). I did nothing to setup 
- Devuan x64 
- Web interface 

## Describe the bug / actual behavior
Entering something like "hea;th" in search control results in "SQL logic error: fts5: syntax error near ";" (1) (500)"

## Expected behavior
More qualified error or something sane

## To Reproduce
See above

## Screenshots
NA

## Notes
NA

**Comment by MageSlayer** [comment]
Are you sure it's fixed?
I've tested using https://github.com/go-shiori/shiori/actions/runs/5918425180 artifacts.
Still the same error.

**Comment by fmartingr** [comment]
Can you try again with https://github.com/go-shiori/shiori/releases/tag/v1.6.0-rc.1?

**Comment by MageSlayer** [comment]
Yes. It's fixed now. Thanks
