### ISSUE TITLE
"Edit bookmark" window is too small

### ISSUE THREAD

**Issue by MageSlayer** [go-shiori/shiori#731]
## Data
- Shiori version 1.6.0-rc.1 (build 1d52569731e72d2dcb4236f3008912b58a310f6d) at 2023-09-11T17:23:40Z
- SQLite
- Devuan x64 
- Web interface 

## Describe the bug / actual behavior
"Edit bookmark" window is too small. On 4K screen it occupies too little space & can't be expanded.

## Expected behavior
Make window be a large percent of browser window or/and allow it to be resizable.

## To Reproduce
Just any bookmark.

## Screenshots
NA

## Notes
NA

**Comment by MageSlayer** [comment]
![Screenshot from 2023-09-14 18-00-43](https://github.com/go-shiori/shiori/assets/583635/42789560-a813-4d3c-8c22-03b8f328ba2a)

**Comment by MageSlayer** [comment]
Yes. I need it as wide as possible.
Something similar to that video.

**Comment by fmartingr** [comment]
> (screenshot)

This size seems ok to me, CSS should be smart enough to adjust with the `<meta name="viewport">` header. I have two screens (one 1080p, other 2k) and it adjust correctly. Also didn't saw any issues with the laptop screen which is HiDPi (almost 4k).

Do you see a problem with the size of the box, the size of the text, or both?

I love the idea of allowing a resizable dialog box (and didn't knew it was that easy!). But we need to account for UX problems like this:
![Screenshot 2023-09-15 at 18 12 21](https://github.com/go-shiori/shiori/assets/812088/6ab91405-ea28-4d9c-aefd-2b11ce1bf161)

**Comment by MageSlayer** [comment]
Please expand it as wide as possible & make resizable.
Personally I hate UIs made to conform to some abstract artistic choices instead of giving a user the entire hardware capabilities.

**Comment by fmartingr** [comment]
> you right. is it good enough to change width to the 20% of screen?
> it will be around 400px for 1080 and 800px in 4k. for now we have fix width-max 400px in all display.
> i should test that on mobile device too.

When I tested it I used `60vw` and `70vh` as max options for width and height, respective, and it looked good. I think that should be a good compromise for now, not making a big impact on the UI/UX.
