### ISSUE TITLE
`make styles-check` return error if you have untrack files

### ISSUE THREAD

**Issue by Monirzadeh** [go-shiori/shiori#737]
## Data
- **Shiori version**: last master branch
- **Database Engine**: sqlite
- **Operating system**: linux
- **CLI/Web interface/Web Extension**: 

## Describe the bug / actual behavior
if you have files that not add to git to track  `make style-check` return error
```
fatal: No names found, cannot describe anything.
CLEANCSS_OPTS=--with-rebase /usr/bin/bash ./scripts/styles_check.sh
❌ git tree is not clean. Please commit all changes before running this script.
make: *** [Makefile:85: styles-check] Error 1
```

## Expected behavior
styles-check  return error if track files not commit.

## To Reproduce
1. Clone master project 
2. run `make style-check`
3. everything work fine
4. create an empty file in root of project test.sh
5. run `make style-check` again
6. you see that error

## Notes
we have some files in project that not ready to add yet or some other is personal script that we use for easier development processes things that we not add to project or `.gitignore` so in this situation we can't use `make style-check` command.

**Comment by fmartingr** [comment]
This is intentional since the script checks the working directory for changes to ensure that there's no changes after running `make styles` in the check script. Maybe we can change that so we only check the status of the generated files?

Note: `make swag-check` works the same way.

**Comment by fmartingr** [comment]
> which directory should monitor for `swag-check`? just `docs/swagger/`?

I believe everything under `docs/swagger` is generated, yes.
