### ISSUE TITLE
1.6.0-RC* webroot does not work properly

### ISSUE THREAD

**Issue by gili-gili** [go-shiori/shiori#751]
## Data

- **Shiori version**: ~~v1.2.5~~ 1.6.0-rc.3
- **Database Engine**: PostgreSQL
- **Operating system**: Arch Linux
- **CLI/Web interface/Web Extension**: do not matter

## Describe the bug / actual behavior

I'm running shiori with systemd and postgresql  
If I set `SHIORI_DIR`, then shiori would ignore `SHIORI_DATABASE_URL` and try to create sqlite database under `SHIORI_DIR`  

## Expected behavior
They should work together.

## To Reproduce

just execute `export xxx=xxx`

## Screenshots

no

## Notes

need further information

**Comment by gili-gili** [comment]
well it seems that shiori doesn't honor `SHIORI_DATABASE_URL` at all  
I tried `export SHIORI_DATABASE_URL=xxx` and `SHIORI_DATABASE_URL=xxx shiori serve` but none of them worked  
Am I doing anything wrong?

**Comment by gili-gili** [comment]
fixed in v1.6.0-rc.3

**Comment by gili-gili** [comment]
And then `--webroot` is not working! Tested in `v1.6.0-rc.2` and `v1.6.0-rc.3`

**Comment by gili-gili** [comment]
Also, in RC3, shiroki won't redirect users to login page automaticly if they were not logged in yet. Here is the log and error messsage
```

2023/10/13 17:24:11 [Recovery] 2023/10/13 - 17:24:11 panic recovered:
error parsing token: token is malformed: token contains an invalid number of segments
/home/runner/work/shiori/shiori/internal/webserver/utils.go:102 (0xcaf6f0)
/home/runner/work/shiori/shiori/internal/webserver/handler-api.go:66 (0xcae718)
/home/runner/work/shiori/shiori/internal/http/routes/legacy.go:37 (0xd73b52)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x979679)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x979667)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x979679)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x979667)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd7833c)
/home/runner/go/pkg/mod/github.com/toorop/gin-logrus@v0.0.0-20210225092905-2c785434f26f/logger.go:43 (0xd78323)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xca06ab)
/home/runner/go/pkg/mod/github.com/gin-contrib/requestid@v0.0.6/requestid.go:48 (0xca0699)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x97855a)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x9781ed)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x977d1c)
/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2938 (0x6e5bcd)
/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2009 (0x6e1ab3)
/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/asm_amd64.s:1650 (0x46b9c0)
```
```
ERROR

error parsing token: token is malformed: token contains an invalid number of segments (500)
```

**Comment by fmartingr** [comment]
The error you experience with the malformed token is solved by #748. Webroot wasn't taken care by the new server I think, let me check if I can do a quick PR.

Thanks for detailing your findings, really appreciated!

**Comment by fmartingr** [comment]
Which reverse proxy are you using? I was thinking about this, and maybe is easier to tell your reverse proxy to avoid sending the prefixed path entirely? That's how I did it in the past on other services of mine.

**Comment by gili-gili** [comment]
Nginx. Currently no rewrite rules applied.

**Comment by gili-gili** [comment]
# Summary

## error parsing token: token is malformed

Fixed in https://github.com/go-shiori/shiori/pull/748 ( I downloaded the artifacts and tested )
However the error log still exists and is a bit annoying
```
2023/10/16 00:00:00 [Recovery] 2023/10/16 - 00:00:00 panic recovered:
session has been expired
/home/runner/work/shiori/shiori/internal/webserver/utils.go:102 (0xcaf830)
/home/runner/work/shiori/shiori/internal/webserver/handler-api.go:66 (0xcae858)
/home/runner/work/shiori/shiori/internal/http/routes/legacy.go:37 (0xd73cb2)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x979679)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x979667)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x979679)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x979667)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xd7849c)
/home/runner/go/pkg/mod/github.com/toorop/gin-logrus@v0.0.0-20210225092905-2c785434f26f/logger.go:43 (0xd78483)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xca06ab)
/home/runner/go/pkg/mod/github.com/gin-contrib/requestid@v0.0.6/requestid.go:48 (0xca0699)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x97855a)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x9781ed)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x977d1c)
/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2938 (0x6e5bcd)
/opt/hostedtoolcache/go/1.21.1/x64/src/net/http/server.go:2009 (0x6e1ab3)
/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/asm_amd64.s:1650 (0x46b9c0)
```

## --webroot only works for static files

First appeared in `v1.6.0-RC1`. Waiting for fix.
Workaround: use both `--webroot` in shiori and rewrite rules provided by reverse proxy software. Example configuration for nginx:
```
    location /shiori {
        rewrite ^/shiori(.*)$ $1 break;
        proxy_pass            http://127.0.0.1:8080;
    }
```
## shiori account won't be deleted after a new account is created

I encountered this when using postgresql in `v1.6.0-RC3`. I have not tested this with sqlite3

**Comment by fmartingr** [comment]
> --webroot only works for static files

Have you tried adding a final slash to the `proxy_pass` directive (without the --webroot flag)?

```
        proxy_pass            http://127.0.0.1:8080/;
```

**Comment by gili-gili** [comment]
> > --webroot only works for static files
> 
> Have you tried adding a final slash to the `proxy_pass` directive (without the --webroot flag)?
> 
> ```
>         proxy_pass            http://127.0.0.1:8080/;
> ```

After adding a slash, now it's working!  
idk why but in versions lower than `v1.6.0-RC1` shiori can handle it correctly without the final slash. Maybe we should remind users of this in the documentation?

**Comment by gili-gili** [comment]
Update: Unfortunately `--webroot` do not work with archived pages.
