### ISSUE TITLE
Option to add existing URL as new bookmark

### ISSUE THREAD

**Issue by rmayergfx** [go-shiori/shiori#755]
Short to explain. There is a landing page:
https://www.maerklin-messagewagons.com/de
old one:
https://web.archive.org/web/20221203063405/https://www.maerklin-messagewagons.com/de

The URL is always the same, but the content changes 2 times a  year.
Is there an option to not override the old bookmark?

**Comment by fmartingr** [comment]
No, since this is a bookmark first, we don't allow duplicates. 

As a workaround you can append a hash to the URL to store it twice: Something like `https://www.maerklin-messagewagons.com/de#2023-10-15`.

**Comment by rmayergfx** [comment]
how can this be done with the webExtension?

**Comment by fmartingr** [comment]
> how can this be done with the webExtension?

Is the webextension reporting a duplicate if you visit a site with the `#random` has? Maybe the extension does some cleanup.

**Comment by rmayergfx** [comment]
i tried to to find out any information about the Hasch (#) in the doc, but don´t find anything about this.
it ist not working with webextionsion or web, adding a hash gives me an error if i try to do this:
![grafik](https://github.com/go-shiori/shiori/assets/105392164/6b8361e5-0651-4be5-84a0-aa11b2101fba)

**Comment by fmartingr** [comment]
I just tried adding a random hash to an URL and it allowed me adding the same URL:


https://github.com/go-shiori/shiori/assets/812088/3747d7e9-ac9c-4035-8511-94c5aa7736cb

**Comment by rmayergfx** [comment]
if i do so, it will fail on my synology and creates an error:
![grafik](https://github.com/go-shiori/shiori/assets/105392164/7e1f671f-9046-4844-aafb-e3b089e46a2d)

**Comment by fmartingr** [comment]
Ok my bad! This workaround will be possible in 1.6.0, it was added by https://github.com/go-shiori/shiori/issues/315.

**Comment by rmayergfx** [comment]
with release 1.7.1 this is now working as expected
added #2024.12.13 to the url and got a second snap
