### ISSUE TITLE
Can Shiori import firefox bookmarks json ?

### ISSUE THREAD

**Issue by accforgithubtest** [go-shiori/shiori#762]
Can Shiori import firefox bookmarks json ?

All docs point to importing from html, but no mention of importing form json.
Apologies if it has been answered, but I havent been able to fins an answer to this easily.

**Comment by fmartingr** [comment]
Not at this time, the import/export systems need to be reworked a bit.

**Comment by fmartingr** [comment]
Closing to focus the conversation in #771
