### ISSUE TITLE
bookmarking pdf  files

### ISSUE THREAD

**Issue by s-frostick** [go-shiori/shiori#77]
If i bookmark a pdf for example http://siteresources.worldbank.org/INTRANETTRADE/Resources/C5.pdf
this causes a huge about of unreadable text to be displayed in both the extract and the cache for the bookmark.

 I presume this is an issue with the go-readability library as i'm guessing it can't parse pdfs. But maybe shiori should detect the url is a pdf and not try to generate an extract or offline version.

**Comment by RadhiFadlillah** [comment]
Since the `ramadhan` branch is merged, this issue should be fixed now. Therefore, I will close this issue. Feels free to reopen it if the issue still exists.
