### ISSUE TITLE
SHIORI_HTTP_SECRET_KEY

### ISSUE THREAD

**Issue by LLKoder** [go-shiori/shiori#782]
## Data
- **Shiori version**: last
- **Database Engine**: sqlite
- **Operating system**: ubuntu
- **CLI/Web interface/Web Extension**: CLI

## Describe the bug / actual behavior
When I run Shiori in docker I get some WARN error:

`SHIORI_HTTP_SECRET_KEY is not set, using random value. This means that all sessions will be invalidated on server restart.`

What do this error mean? How can I to fix it?

**Comment by fmartingr** [comment]
Hey @LLKoder, you need to set the `SHIORI_HTTP_SECRET_KEY` environment variable to something random to use as key for the session tokens. You can generate a pesudo-random string using `openssl`/`pwgen` or any number of tools online.

**Comment by fmartingr** [comment]
Shiori generates one random every run, but for security purposes it must me set by the user. It is used to sign the sessions for the users (the authentication used to interact with the API).

How are you deploying shiori? docker compose/docker run? It something like this:
```
# Generate random string
$ openssl rand -hex 32
4c9598950d692a846977b5bc1dd31f3fed1afe1b3252cb8019e7aa914e2a1297

#  Run shiori
$ docker run --env SHIORI_HTTP_SECRET_KEY=4c9598950d692a846977b5bc1dd31f3fed1afe1b3252cb8019e7aa914e2a1297 ghcr.io/go-shiori/shiori:dev
```
