### ISSUE TITLE
New Android Client App for go-shiori/shiori

### ISSUE THREAD

**Issue by DesarrolloAntonio** [go-shiori/shiori#813]
Hello go-shiori team!

I'm an Android/iOS app developer. I wanted to let you know that I have created a client app for go-shiori in my free time, and it's now available on the Play Store.

I thought it would be great to have a mobile version of go-shiori, so I got to work on it. My plan is to release the source code soon.

Here's the link to the Play Store for you to check it out:
https://play.google.com/store/apps/details?id=com.desarrollodroide.pagekeeper

Would really appreciate your feedback or suggestions for improvements. Looking forward to your thoughts!

Best regards,

**Comment by Katarn** [comment]
Very cool! I will try the application when the source code is available.

Does the application support HTTP Basic Auth?

**Comment by DesarrolloAntonio** [comment]
Thank you for the feedback. I will try to implement those suggestions as soon as I can.

**Comment by DesarrolloAntonio** [comment]
I have released a new version 1.02:

- Bug fixes
- Now it first loads from cache and then updates in the background if there is new content

**Comment by DesarrolloAntonio** [comment]
Source code releases in github:
https://github.com/DesarrolloAntonio/Shiori-Android-Client

**Comment by DesarrolloAntonio** [comment]
> Hey Antonio, I don't use an Android phone as primary but unshelved my old One Plus just to install and check this out, looking good!
> 
> Are you aware of the API rework going on? Some of the API endpoints are going to change over time and the new API will be documented following the OpenAPI spec. From 1.6.0 forward you will have a `/system/liveness` endpoint that will contain the version of the server, that will be useful to deal with the new API routes.
> 
> If you have any questions or suggestions for the API as a consumer let me know.
> 
> Leaving this as an issue to add a section in the usage with community clients.

Yes, I plan to update the API as soon as I can.

**Comment by MrColumbo** [comment]
when i try to share a link with it, then it only works when i recently logged in. 

It might nice if the app checks if session expired and logs in and then then submits the URL to shiori since currently it just shows a spinning wheel which stops after a while but nothing happens (if the session expired)

**Comment by DesarrolloAntonio** [comment]
> when i try to share a link with it, then it only works when i recently logged in.
> 
> It might nice if the app checks if session expired and logs in and then then submits the URL to shiori since currently it just shows a spinning wheel which stops after a while but nothing happens (if the session expired)

You're right, I will fix the bug.

**Comment by Else00** [comment]
Will you ever do a client for iOS?
