### ISSUE TITLE
Hosted shiori

### ISSUE THREAD

**Issue by gregf** [go-shiori/shiori#82]
Can I host shori on a remote server plus use the cli commands. Meaning use the cli as a thin client to the api? I don't see how I can configure it currently to point to a remote location it appears it has to be hosted locally?

**Comment by mnxn** [comment]
If you're using Heroku, you do `heroku run somecommand` through your machine or the dashboard: https://devcenter.heroku.com/changelog-items/1137. For example, to add an account you would do `heroku run shiori account add accountname`.

Most cloud providers let you do this in one form or another. I know Microsoft Azure has a way to get into the console through one of the menu options. 

If you're hosting on your own servers, you can `ssh` into it and run commands that way.
