### ISSUE TITLE
Image Caching Issue When Re-creating Bookmarks

### ISSUE THREAD

**Issue by DesarrolloAntonio** [go-shiori/shiori#833]
## Description
I've encountered a problem regarding image caching within the Shiori bookmark management app. Whenever I create a bookmark, delete it, and then create another one, the image from the first bookmark persists and is incorrectly associated with the new bookmark.

## Steps to Reproduce
1. Create a bookmark with a specific image.
2. Delete the bookmark created in step 1.
3. Create a new bookmark.

## Expected Behavior
The new bookmark should not retain or display the image from the previously deleted bookmark. Instead, it should either have no image or display a new image if one is specified during the creation of the new bookmark.

## Actual Behavior
The image from the first bookmark is displayed for the new bookmark, indicating an issue with how images are cached and reused after a bookmark is deleted.

- Create the numerb 4 bookmark
![image](https://github.com/go-shiori/shiori/assets/7002198/d3536d25-7812-4b06-bed4-53c61593bae0)

- Remove the bookmark an create another
![image](https://github.com/go-shiori/shiori/assets/7002198/6baf3e02-94ed-4e02-b8c7-5b7be405c116)

**Comment by fmartingr** [comment]
I think this was solved in https://github.com/go-shiori/shiori/pull/775
