### ISSUE TITLE
SQLite Bind Address already in use

### ISSUE THREAD

**Issue by ordinarysimplicity** [go-shiori/shiori#853]
## Data
- **Shiori version**: Docker Latest
- **Database Engine**: SQLite
- **Operating system**: Linux/Dcoker

This probably isn't actually an issue with Shiori, but some kind of screw up on my part. I am trying to set up Shiori in a Docker container using SQLite, however, I realized that the .db file is not being created. So I tried running " docker exec -it shiori shiori serve" to see if I could get it to start/create the .db file, but I get an error message:
"INFO[2024-03-04T05:11:08Z] Serve shiori in :8080 /                      
FATA[2024-03-04T05:11:08Z] Server error: listen tcp :8080: bind: address already in use "

docker-compose.yml:
`  shiori:
    image: ghcr.io/go-shiori/shiori:latest
    container_name: shiori
        restart: "unless-stopped"
    networks:
     - udms
    ports:
      - 8088:8080
    volumes:
      - $DOCKERDIR/appdata/shiori:/shiori
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - $DOCKERDIR/appdata/shiori=/shiori`

I'm not sure how to fix this. I thought maybe it was a conflict with another docker container that also uses SQLite, so I stopped that container with docker compose down command. But that doesn't seem to fix the error.

**Comment by ordinarysimplicity** [comment]
docker ps output:
https://gist.github.com/ordinarysimplicity/6cf7f3ad9111c259c7ac73bf0f92ab2a

I have several services that use 8080 internally, but I didn't think the *internal* ports could conflict across containers... maybe I'm wrong in thinking that? Though this would be the first time I've had this issue.

**Comment by fmartingr** [comment]
Using `docker exec -it shiori shiori serve` over the running shiori container won't work because Shiori is already running on port 8080. Can you share the container logs?
