### ISSUE TITLE
Shiori auto increasment not work currectly on sqlite database

### ISSUE THREAD

**Issue by Monirzadeh** [go-shiori/shiori#892]
## Data
- **Shiori version**: 1.6.2
- **Database Engine**: sqlite
- **Operating system**: linux
- **CLI/Web interface/Web Extension**: all of them

## Describe the bug / actual behavior
if you add just first bookmark it will get ID 1
now if you remove that bookmark and add new bookmark it again get same ID number 1

## Expected behavior
shiori always should create uniq id that not ever use.

## To Reproduce
1. add bookmark a that you will get id 1 for that
2. delete that bookmark
3. add bookmark b
4. you will get id 1 again instead of 2 for bookmark b

## Notes
it happen just in sqlite

**Comment by fmartingr** [comment]
Related documentation: https://www.sqlite.org/autoinc.html
