### ISSUE TITLE
Can't use anymore after last upgrade

### ISSUE THREAD

**Issue by edied2002** [go-shiori/shiori#901]
## Data
- **Shiori version**: 1.6.4
- **Database Engine**:default
- **Operating system**: docker container
- **CLI/Web interface/Web Extension**: 

## Describe the bug / actual behavior
After last upgrade the web doesn't load and I can see this logs:
time="2024-05-04T14:22:32Z" level=warning msg="SHIORI_HTTP_SECRET_KEY is not set, using random value. This means that all sessions will be invalidated on server restart."
time="2024-05-04T14:22:32Z" level=fatal msg="Error running migration" error="failed to run migration from 0.0.0 to 0.1.0: failed to run transaction: failed to execute migration 0.0.0 to 0.1.0: attempt to write a readonly database (8)"
## Expected behavior
Normal behavior

## To Reproduce
I did nothing, just upgrade the container

**Comment by fmartingr** [comment]
Hey @edied2002, did you solve this? It was caused by Shiori? 

From the logs you provide that's a change in the migration system for the next release. I upgraded my own instances without issues, from which version were you upgrading to that?

**Comment by edied2002** [comment]
> Hey @edied2002, did you solve this? It was caused by Shiori?
> 
> From the logs you provide that's a change in the migration system for the next release. I upgraded my own instances without issues, from which version were you upgrading to that?

Sorry, I searched and this was the problem as in this another post: https://github.com/go-shiori/shiori/issues/546
