### ISSUE TITLE
Shiori can't migrate from 1.6.3 to last commit in master, if you use Postgres or Mariadb

### ISSUE THREAD

**Issue by Monirzadeh** [go-shiori/shiori#904]
## Data
- **Shiori version**: last commit in master branch c107e974caa4c983544856ef76c70c00f708dc8e
- **Database Engine**: postgress
- **Operating system**: linux
- **CLI/Web interface/Web Extension**: Web interface

## Describe the bug / actual behavior
Shiori can't done migration from last release [1.6.3](https://github.com/go-shiori/shiori/releases/tag/v1.6.3) to last we have in master (currently is commit c107e974caa4c983544856ef76c70c00f708dc8e) if you use postgres database and you will get this error 
```
ERROR:  relation "shiori_system" does not exist at character 37
```

## Expected behavior
Shiori can migrate without any error if you use Postgres

## To Reproduce
1. Get last Shiori release [1.6.3](https://github.com/go-shiori/shiori/releases/tag/v1.6.3)
2.  Run that with with a pg database with `SHIORI_DATABASE_URL`
3.  Shutdown Shiori 
4. Clone Shiori repository and try to setup same pg database with `SHIORI_DATABASE_URL` and run with `go run main.go server `
5. As you see get bellow error in postgress log and Shiori not run
 `ERROR:  relation "shiori_system" does not exist at character 37`

## Notes
It not happen for Sqlite and happen in pg and mariadb

**Comment by fmartingr** [comment]
If my assumption is correct is weird that is not happening for SQLite, should happen for all engines. I will take a look at this later in the date or tomorrow, should be an easy fix.

**Comment by fmartingr** [comment]
Hey @Monirzadeh I can't replicate this. I create my PSQL database with 1.6.3, when I run the `master` branch I get the `shiori_system` database properly.

I got a different error though: https://github.com/go-shiori/shiori/pull/906
