### ISSUE TITLE
"View Original" link in the archive view references the same page

### ISSUE THREAD

**Issue by greenfork** [go-shiori/shiori#930]
## Data
- **Shiori version**: d05188b666a28a02a83c6d050eaa91e4bf277386
- **Database Engine**: SQLite
- **Operating system**: OpenBSD
- **CLI/Web interface/Web Extension**: Web interface

## Describe the bug / actual behavior
A link "View Original" on the page like https://links.greenfork.me/bookmark/4/archive references the same https://links.greenfork.me/bookmark/4/archive link.

```html
<body class="archive">
    <div id="shiori-archive-header" class="header">
        <p id="shiori-logo"><span>栞</span>shiori</p>
        <div class="spacer"></div>
        <a href="" target="_blank">View Original</a>
        
        <a href="[/bookmark/4/content](view-source:https://links.greenfork.me/bookmark/4/content)">View Readable</a>
        
    </div>
    <iframe src="[/bookmark/4/archive/file/](view-source:https://links.greenfork.me/bookmark/4/archive/file/)" frameborder="0"></iframe>
</body>
```

See `<a href="" target="_blank">View Original</a>`.

## Expected behavior
Should be a link to the original resource.

## To Reproduce
1. Add a page
2. Visit its archive
3. Click "View Original"

## Notes

The link to view the original works fine from the home page and from the "readable" page.

**Comment by fmartingr** [comment]
Thanks for the report, I reproduced this locally.
