### ISSUE TITLE
Provide debug docker images to the able to run other commands inside the container

### ISSUE THREAD

**Issue by JER-ry** [go-shiori/shiori#937]
https://github.com/go-shiori/shiori/blob/9aa8332c3c464276fbc37e46f02d1e72614be774/docs/Usage.md?plain=1#L38

There's no `sh` in the image currently, so this command gives an error. Maybe change it to

> `docker exec -it shiori [command]`, where `[command]` is something like `shiori pocket 1.html`.

**Comment by fmartingr** [comment]
Relates to #964

**Comment by essys** [comment]
How can the export or import function be used, as we are currently unable to exec into the container?
I remember in past versions it was possible to _docker exec -it shiori /bin/ash_ into the container as it was alpine based.
Is there a possibility that we can currently use the export function?

**Comment by essys** [comment]
It's still not possivle to exec into the container to run exports?
How can export cmds currently be executed?

I cannot find anything in current docs:
https://github.com/go-shiori/shiori/tree/master/docs

**Comment by fmartingr** [comment]
We now create multi-tag images. You can preppend `alpine-` to the tag you are using (example: `alpine-v1.7.3`) and you have an Alpine OS at your disposal.
