### ISSUE TITLE
internal/database/database.go:59:10: undefined: OpenSQLiteDatabase

### ISSUE THREAD

**Issue by lifepillar** [go-shiori/shiori#947]
## Data
- **Shiori version**: v1.7.0 branch
- **Database Engine**: SQLite (the default).
- **Operating system**: FreeBSD 14
- **CLI/Web interface/Web Extension**: CLI

## Describe the bug / actual behavior

Trying to build Shiori from source results in:

    internal/database/database.go:59:10: undefined: OpenSQLiteDatabase

## Expected behavior
The build should succeed.

## To Reproduce
1. `git clone https://github.com/go-shiori/shiori.git`
2. `git checkout v1.7.0`
3. `go build`

## Notes
Likely not a bug; rather, I'm missing something in the build process.

**Comment by lifepillar** [comment]
The culprit is 02247b215b2fa1c1c18f651561092290ed2a5058. I've got around the error by reinstating `OpenSQLiteDatabase()` in `internal/database/sqlite.go`. This seems a FreeBSD-specific problem.

**Comment by fmartingr** [comment]
> The culprit is [02247b2](https://github.com/go-shiori/shiori/commit/02247b215b2fa1c1c18f651561092290ed2a5058). I've got around the error by reinstating `OpenSQLiteDatabase()` in `internal/database/sqlite.go`. This seems a FreeBSD-specific problem.

OpenBSD builds were broken so we removed the unimportant CGO dependencies and isolated the SQLite library into it's own build under `internal/database/sqlite_openbsd.go`. Unsure what's the problem could be with freebsd, maybe just adding the build flag to the same file to use it under freebsd is enough?

https://github.com/go-shiori/shiori/blob/master/internal/database/sqlite_openbsd.go#L1-L2

**Comment by lifepillar** [comment]
>If FreeBSD works with nonCGO we can add it into the noncgo build flags

I can confirm that this way Shiori builds.

**Comment by fmartingr** [comment]
> > If FreeBSD works with nonCGO we can add it into the noncgo build flags
> 
> I can confirm that this way Shiori builds.

Would you be open to submit a PR with those changes?
