### ISSUE TITLE
Wrong application path for asset/eventBus.js

### ISSUE THREAD

**Issue by nakal** [go-shiori/shiori#962]
## Data
- **Shiori version**: 1.7.0
- **Database Engine**: PostgreSQL
- **Operating system**: FreeBSD
- **CLI/Web interface/Web Extension**: Web interface

## Describe the bug / actual behavior
Shiori server is running with Nginx in the subpath `/shiori`. Most assets are loaded properly except `eventBus.js`. The relevant piece shows that the asset url might be wrong:

```
<script type="module">
                import basePage from "./assets/js/page/base.js";                                  import pageHome from "./assets/js/page/home.js";
                import pageSetting from "./assets/js/page/setting.js";
                import customDialog from "./assets/js/component/dialog.js";
        import EventBus from "../assets/js/component/eventBus.js";
```

In the last import you can see "../".

## Expected behavior
The asset should probably be loaded from the correct webroot.

## To Reproduce
1. Go to 'https://host/webroot'
2. Examine the web page source.

**Comment by isamert** [comment]
I am also experiencing this, as a workaround I use the following in my nginx configuration for shiori:

```
        sub_filter ../assets/js/component/eventBus.js ./assets/js/component/eventBus.js;
```
