### ISSUE TITLE
Using SHIORI_DATABASE_URL fails silent and default (SQLite) is used

### ISSUE THREAD

**Issue by IeP4nieF** [go-shiori/shiori#978]
## Data
- **Shiori version**: ```# shiori version
Error: unknown command "version" for "shiori"
Run 'shiori --help' for usage.
FATA[0000] unknown command "version" for "shiori"``` (I'm using the latest docker image.)
- **Database Engine**: Wanted: PostgreSQL, Used: SQLite
- **Operating system**: linux
- **CLI/Web interface/Web Extension**: ?

## Describe the bug / actual behavior
I'm using `podman-compose` to run the latest docker image of shiori. In `compose.yml` there is  a line

    SHIORI_DATABASE_URL='postgres://shiori:secretpassword@postgresql.domainname/shiori?sslmode=require'

and inside the container I get:
```
# echo $SHIORI_DATABASE_URL
postgres://shiori:secretpassword@postgresql.domainname/shiori?sslmode=require
```
I thought that shiori is using this database-connection, because the only log-message I get when starting the container is:

    [shiori] | time="2024-09-08T09:24:29+01:00" level=info msg="Serve shiori in :8080"

But today I looked at this Database and there are no tables! Shiori is using SQLite.

## Expected behavior

If `SHIORI_DATABASE_URL` is set and there is a problem with connecting to this database, shiori should stop working instead of using the default (SQLite). Otherwise no one will recognize the error.

## To Reproduce
Use shiori with `SHIORI_DATABASE_URL` set. Probably you need a problem with this connection too. But I don't know because there are no logs! The only log-message I get with `podman-compose logs` is the message shown above. BTW: How to set loglovel to debug?

**Comment by fmartingr** [comment]
Hey @IeP4nieF, this should be working as you are describing, what I think is that you are running an older Shiori version, since the `version` command was added in 1.6.0 (we are on 1.7.1 as this time) and you don't have that command.

Can you try pulling the latest version: `docker pull ghcr.io/go-shiori/shiori:v1.7.1` and try again?

**Comment by IeP4nieF** [comment]
Thank you @fmartingr! I don't now why, but I used `docker.io/radhifadlillah/shiori:latest` instead of `ghcr.io/go-shiori/shiori:latest`. After changeing to `ghcr.io/go-shiori/shiori:latest` Shiori now uses the Postgresql server.

(Now there is another issue, but I'll open another issue for that.)
