### ISSUE TITLE
All users share the same shiori list and data

### ISSUE THREAD

**Issue by acirep** [go-shiori/shiori#982]
## Data
- **Shiori version**: Shiori version 1.6.3 (build FreeBSD) at 2024-08-09T01:03:16
- **Database Engine**:  SQLite 
- **Operating system**: FreeBSD 14.1 p5
- **CLI/Web interface/Web Extension**: Web interface

## Describe the bug / actual behavior
Every user that I create in shiori is seeing the same list of bookmarks. Had one user and added some links as that user. After that created two new users - one owner and another "visitor" and after logging in as either new user I still see the link list of the original owner user.

## Expected behavior
Multiple users should have multiple lists...

## To Reproduce
Already explained.

**Comment by fmartingr** [comment]
This is, at least for now, how shiori works. It's a central repository for bookmarks. The difference between an admin and a visitor is that only de admin is capable of modifying the bookmarks database while the visitor can only read.

To check progress on the multi-user support please subscribe to #516
