### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by rndmh3ro** [go-shiori/shiori#988]
## Describe the bug / actual behavior

The latest published release v1.7.0 is from June. There are some bugfixes (e.g. https://github.com/go-shiori/shiori/pull/971) that I need to get shiori running again.

I know that I can build it myself (and I did), but I'm using [yunohost](https://yunohost.org/) to host shiori and it only uses releases, not development-versions.

## Expected behavior
A new release (maybe automated?)

Thank you!

**Comment by fmartingr** [comment]
Let me check what's on `master` at the moment, if there's nothing breaking (it shouldn't be since you are using it) I think I can do a new hotfix release.

**Comment by fmartingr** [comment]
Here you are :) Let me know if something else is not working with the yunohost integration.

https://github.com/go-shiori/shiori/releases/tag/v1.7.1

**Comment by rndmh3ro** [comment]
Awesome, thank you. Works like a charm!
