### ISSUE TITLE
Postresql: Start of Shiori fails with "failed to run migration from 0.2.0 to 0.3.0:" after fresh installation

### ISSUE THREAD

**Issue by IeP4nieF** [go-shiori/shiori#996]
## Data
- **Shiori version**: 1.7.1 (build 2315f0da403a2e5dca6841e83f0fac5f52e4a18f)
- **Database Engine**: Postgresql
- **Operating system**: Debian with podman-compose
- **CLI/Web interface/Web Extension**: no

## Describe the bug / actual behavior
After a fresh installation I'm starting Shiori for the first time and and get:

```
[shiori] | 2024/10/13 02:09:07 error during commit: sql: transaction has already been committed or rolled back
[shiori] | 2024/10/13 02:09:07 error during commit: sql: transaction has already been committed or rolled back
[shiori] | time="2024-10-13T02:09:07+01:00" level=fatal msg="Error running migration" error="failed to run migration from 0.2.0 to 0.3.0: failed to add has_content column to book mark table: pq: column »has_content« of relation »bookmark« exists already"
```

There is not data nor any relations in the database before I start Shiori.

## Expected behavior
Shiori should start without errors.

## To Reproduce
Use the latest docker-image with postgresql:

    SHIORI_DATABASE_URL='postgres://shiori:secretpassword@postgresql.domainname/shiori?sslmode=require'

in `compose.yml`.

**Comment by fmartingr** [comment]
Could you run this three queries in your psql server and provide the output? Your output, even if in English, is sightly differnent than mine.

```
SHOW lc_ctype;
SHOW lc_collate;
SHOW server_encoding;
```
